/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package io.github.awakelab.awake.asset.shaderdsl

import kotlin.test.Test
import kotlin.test.assertEquals

/** Full-text goldens: any emitter change shows up as an exact diff here, on every platform. */
class WgslEmissionTest {

    @Test
    fun triangleShaderEmitsGoldenWgsl() {
        assertEquals(TRIANGLE_GOLDEN, TriangleShader.emitWgsl())
    }

    @Test
    fun checkerShaderEmitsGoldenWgsl() {
        assertEquals(CHECKER_GOLDEN, CheckerShader.emitWgsl())
    }
}

private val TRIANGLE_GOLDEN = """
// Generated by Awake Lab ASL (:awake:asset:shader-dsl) -- shader 'triangle'.
// Do not edit: change the Kotlin definition, re-record with AWAKE_RECORD_SHADERS=1.
// Deliberately undated so record runs are byte-reproducible.

const AMBIENT_STRENGTH : f32 = 0.08;

struct Uniforms {
  mvp : mat4x4<f32>,
  lightDirection : vec4f,
  lightColor : vec4f,
}
@binding(0) @group(0) var<uniform> uniforms : Uniforms;

struct VertexOutput {
  @builtin(position) position : vec4f,
  @location(0) color : vec3f,
  @location(1) normal : vec3f,
}

@vertex
fn vertexMain(
  @location(0) inPosition : vec3f,
  @location(1) inNormal : vec3f,
  @location(2) inColor : vec3f,
) -> VertexOutput {
  var output : VertexOutput;
  output.position = uniforms.mvp * vec4f(inPosition, 1.0);
  output.color = inColor;
  output.normal = inNormal;
  return output;
}

@fragment
fn fragmentMain(@location(0) color : vec3f, @location(1) normal : vec3f) -> @location(0) vec4f {
  let n = normalize(normal);
  let l = normalize(uniforms.lightDirection.xyz);
  let diffuse = max(dot(n, l), 0.0);
  let shade = AMBIENT_STRENGTH + (1.0 - AMBIENT_STRENGTH) * diffuse;
  let lit = color * shade * uniforms.lightColor.xyz;
  let mapped = lit / (lit + vec3f(1.0));
  return vec4f(mapped, 1.0);
}
""".trimStart()

private val CHECKER_GOLDEN = """
// Generated by Awake Lab ASL (:awake:asset:shader-dsl) -- shader 'checker'.
// Do not edit: change the Kotlin definition, re-record with AWAKE_RECORD_SHADERS=1.
// Deliberately undated so record runs are byte-reproducible.

struct Uniforms {
  tiles : vec4f,
  colorA : vec4f,
  colorB : vec4f,
}
@binding(0) @group(0) var<uniform> uniforms : Uniforms;

struct VertexOutput {
  @builtin(position) position : vec4f,
  @location(0) uv : vec2f,
}

@vertex
fn vertexMain(@location(0) inPosition : vec3f, @location(1) inUv : vec2f) -> VertexOutput {
  var output : VertexOutput;
  output.position = vec4f(inPosition, 1.0);
  output.uv = inUv;
  return output;
}

@fragment
fn fragmentMain(@location(0) uv : vec2f) -> @location(0) vec4f {
  let cell = floor(uv * uniforms.tiles.x);
  let parity = fract((cell.x + cell.y) * 0.5) * 2.0;
  return mix(uniforms.colorA, uniforms.colorB, parity);
}
""".trimStart()
