// Copyright (c) Ron June Valdoz
// SPDX-License-Identifier: Apache-2.0
package io.github.ronjunevaldoz.awake.ui.tailwind

import io.github.ronjunevaldoz.awake.ui.Dp
import io.github.ronjunevaldoz.awake.ui.dp

/**
 * Generated by `:awake:engine:ui:tailwind-generator` -- do not hand-edit. Re-run that module's `main()` and commit the diff if the vendored scale changes.
 */
object Tw {
    /**
     * Tailwind's default spacing scale (35 steps, "0" through "96") -- see `tailwindSpacingScalePx` in `:awake:engine:ui:tailwind-generator` for the vendored source and why radius isn't included here.
     */
    object Spacing {
        /**
         * Tailwind scale step `0` = 0.0px.
         */
        val s0: Dp = 0.0f.dp

        /**
         * Tailwind scale step `px` = 1.0px.
         */
        val px: Dp = 1.0f.dp

        /**
         * Tailwind scale step `0.5` = 2.0px.
         */
        val s0_5: Dp = 2.0f.dp

        /**
         * Tailwind scale step `1` = 4.0px.
         */
        val s1: Dp = 4.0f.dp

        /**
         * Tailwind scale step `1.5` = 6.0px.
         */
        val s1_5: Dp = 6.0f.dp

        /**
         * Tailwind scale step `2` = 8.0px.
         */
        val s2: Dp = 8.0f.dp

        /**
         * Tailwind scale step `2.5` = 10.0px.
         */
        val s2_5: Dp = 10.0f.dp

        /**
         * Tailwind scale step `3` = 12.0px.
         */
        val s3: Dp = 12.0f.dp

        /**
         * Tailwind scale step `3.5` = 14.0px.
         */
        val s3_5: Dp = 14.0f.dp

        /**
         * Tailwind scale step `4` = 16.0px.
         */
        val s4: Dp = 16.0f.dp

        /**
         * Tailwind scale step `5` = 20.0px.
         */
        val s5: Dp = 20.0f.dp

        /**
         * Tailwind scale step `6` = 24.0px.
         */
        val s6: Dp = 24.0f.dp

        /**
         * Tailwind scale step `7` = 28.0px.
         */
        val s7: Dp = 28.0f.dp

        /**
         * Tailwind scale step `8` = 32.0px.
         */
        val s8: Dp = 32.0f.dp

        /**
         * Tailwind scale step `9` = 36.0px.
         */
        val s9: Dp = 36.0f.dp

        /**
         * Tailwind scale step `10` = 40.0px.
         */
        val s10: Dp = 40.0f.dp

        /**
         * Tailwind scale step `11` = 44.0px.
         */
        val s11: Dp = 44.0f.dp

        /**
         * Tailwind scale step `12` = 48.0px.
         */
        val s12: Dp = 48.0f.dp

        /**
         * Tailwind scale step `14` = 56.0px.
         */
        val s14: Dp = 56.0f.dp

        /**
         * Tailwind scale step `16` = 64.0px.
         */
        val s16: Dp = 64.0f.dp

        /**
         * Tailwind scale step `20` = 80.0px.
         */
        val s20: Dp = 80.0f.dp

        /**
         * Tailwind scale step `24` = 96.0px.
         */
        val s24: Dp = 96.0f.dp

        /**
         * Tailwind scale step `28` = 112.0px.
         */

        val s28: Dp = 112.0f.dp

        /**
         * Tailwind scale step `32` = 128.0px.
         */
        val s32: Dp = 128.0f.dp

        /**
         * Tailwind scale step `36` = 144.0px.
         */
        val s36: Dp = 144.0f.dp

        /**
         * Tailwind scale step `40` = 160.0px.
         */
        val s40: Dp = 160.0f.dp

        /**
         * Tailwind scale step `44` = 176.0px.
         */
        val s44: Dp = 176.0f.dp

        /**
         * Tailwind scale step `48` = 192.0px.
         */
        val s48: Dp = 192.0f.dp

        /**
         * Tailwind scale step `52` = 208.0px.
         */
        val s52: Dp = 208.0f.dp

        /**
         * Tailwind scale step `56` = 224.0px.
         */
        val s56: Dp = 224.0f.dp

        /**
         * Tailwind scale step `60` = 240.0px.
         */
        val s60: Dp = 240.0f.dp

        /**
         * Tailwind scale step `64` = 256.0px.
         */
        val s64: Dp = 256.0f.dp

        /**
         * Tailwind scale step `72` = 288.0px.
         */
        val s72: Dp = 288.0f.dp

        /**
         * Tailwind scale step `80` = 320.0px.
         */
        val s80: Dp = 320.0f.dp

        /**
         * Tailwind scale step `96` = 384.0px.
         */
        val s96: Dp = 384.0f.dp
    }
}
