from __future__ import annotations

from _models import ExternalFunction, Param, ParsedFile
from _parser import jni_function_name
from _struct_gen import generate_all_struct_blocks
from _types import (
    _MAKE_HELPER_MAP,
    UnknownTypeError,
    _is_nullable,
    _needs_exception_check,
    map_param_type,
    map_return_type,
)


def _cpp_var_name(param: Param, info) -> str:
    if info.is_handle:
        return f"{param.name}_ptr"
    return f"{param.name}_val"


_FILE_HEADER = """// AUTO-GENERATED by jni-binding-generator.py — DO NOT EDIT.
// Source: {source}
//
// Regenerate with:  ./gradlew generateJniBindings   (or run the script directly)
// Hand-written logic belongs in the corresponding *-jni.cpp, not here.

#include <jni.h>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstdint>

#include "jni-utils.h"
"""

_TEST_FILE_HEADER = """\
// AUTO-GENERATED by jni-binding-generator.py — DO NOT EDIT.
// Source: {source}
//
// Compile-time type check for jni-utils.h helpers used by {source}.
// Every helper call lives inside ``if (false)`` so the compiler type-checks
// the call without executing it — any signature mismatch is a compile error.
//
// Compile (syntax check only):
//   clang++ -std=c++17 -fsyntax-only \\
//       -I$JAVA_HOME/include -I$JAVA_HOME/include/$(uname -s | tr '[:upper:]' '[:lower:]') \\
//       -I<dir-containing-jni-utils.h> {basename}

#include <jni.h>
#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "jni-utils.h"

#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic ignored "-Wunused-variable"
#endif
"""

# Zero / null value for each JNI type, used in compile-check stubs.
_JNI_ZERO: dict[str, str] = {
    "jstring": "nullptr",
    "jobject": "nullptr",
    "jobjectArray": "nullptr",
    "jbyteArray": "nullptr",
    "jshortArray": "nullptr",
    "jintArray": "nullptr",
    "jlongArray": "nullptr",
    "jfloatArray": "nullptr",
    "jdoubleArray": "nullptr",
    "jbooleanArray": "nullptr",
}

# Enum return comment — tells the native author how to look up the enum instance.
_ENUM_RETURN_COMMENT = (
    "// Return: get a {name} enum instance via JNI, e.g.:\n"
    '//   jclass _ec = env->FindClass("{jvm_path}");\n'
    '//   jmethodID _vm = env->GetStaticMethodID(_ec, "values", "()[L{jvm_path};");\n'
    "//   jobjectArray _va = (jobjectArray)env->CallStaticObjectMethod(_ec, _vm);\n"
    "//   return env->GetObjectArrayElement(_va, your_ordinal);"
)


def _enum_return_comment(name: str, package: str) -> str:
    jvm = (package.replace(".", "/") + "/" + name) if package else name
    return _ENUM_RETURN_COMMENT.format(name=name, jvm_path=jvm)


def generate_function(parsed: ParsedFile, func: ExternalFunction) -> str:
    known_enums = parsed.enum_names
    known_structs = parsed.struct_types

    base_rt = func.return_type.rstrip("?").strip() if func.return_type else None
    is_struct_return = base_rt is not None and base_rt in known_structs
    is_enum_return = base_rt is not None and base_rt in known_enums

    if is_struct_return:
        ret_jni, ret_empty = "jobject", "nullptr"
    else:
        ret_jni, ret_empty = map_return_type(func.return_type, known_enums, parsed.typealiases)

    jni_name = jni_function_name(parsed.package, parsed.class_name, func.name)
    receiver = "jclass clazz" if parsed.is_static else "jobject thiz"
    ret_stmt = f"return {ret_empty};" if ret_empty else "return;"

    # --- Signature ---
    sig_params = ["JNIEnv* env", receiver]
    for p in func.params:
        base = p.kotlin_type.rstrip("?").strip()
        if base in known_structs:
            sig_params.append(f"jobject {p.name}")
        else:
            info = map_param_type(p.kotlin_type, known_enums, parsed.typealiases)
            sig_params.append(f"{info.jni_type} {p.name}")
    signature = ",\n        ".join(sig_params)

    lines: list[str] = []
    lines.append(f'extern "C" JNIEXPORT {ret_jni} JNICALL')
    lines.append(f"{jni_name}(")
    lines.append(f"        {signature}) {{")

    # --- Marshalling ---
    marshalled: list[tuple[Param, object, str]] = []
    real_params = [
        p
        for p in func.params
        if p.kotlin_type.rstrip("?").strip() in known_structs
        or map_param_type(p.kotlin_type, known_enums, parsed.typealiases).convert is not None
    ]
    if real_params:
        lines.append("    // --- Marshalling ---")
    for p in real_params:
        base = p.kotlin_type.rstrip("?").strip()
        if base in known_structs:
            var = f"{p.name}_val"
            lines.append(f"    JNI_{base} {var} = extract_{base}(env, {p.name});")
            marshalled.append((p, None, var))  # None → struct (no TypeInfo)
        else:
            info = map_param_type(p.kotlin_type, known_enums, parsed.typealiases)
            var = _cpp_var_name(p, info)
            expr = info.convert.format(env="env", var=p.name)
            lines.append(f"    {info.cpp_type} {var} = {expr};")
            if _needs_exception_check(info):
                lines.append(f"    if (env->ExceptionCheck()) {ret_stmt}")
            marshalled.append((p, info, var))

    # --- Error handling ---
    checks: list[str] = []
    for p, info, var in marshalled:
        if _is_nullable(p.kotlin_type):
            continue
        if info is None:
            # Struct param — check the raw jobject for null
            checks.append(
                f"    if (!{p.name}) {{\n"
                f'        throw_illegal_argument(env, "{func.name}: {p.name} must not be null");\n'
                f"        {ret_stmt}\n"
                f"    }}"
            )
        elif info.is_handle:
            checks.append(
                f"    if (!{var}) {{\n"
                f'        throw_illegal_state(env, "{func.name}: {p.name} not initialized");\n'
                f"        {ret_stmt}\n"
                f"    }}"
            )
        elif info.is_string:
            checks.append(
                f"    if ({var}.empty()) {{\n"
                f'        throw_illegal_argument(env, "{func.name}: {p.name} is required");\n'
                f"        {ret_stmt}\n"
                f"    }}"
            )
    if checks:
        lines.append("")
        lines.append("    // --- Error handling ---")
        lines.extend(checks)

    # --- Body stub ---
    lines.append("")
    lines.append("    // --- TODO: hand-written native logic ---")
    lines.append("    // Call into your native library using the marshalled values above.")
    if is_struct_return:
        lines.append(f"    // Return: use make_{base_rt}(env, yourResult) to build the jobject.")
    elif is_enum_return:
        lines.append(_enum_return_comment(base_rt, parsed.package))
    else:
        make_fn = _MAKE_HELPER_MAP.get(base_rt or "", (None, None))[0]
        if make_fn:
            lines.append(f"    // Return: use {make_fn}(env, yourResult) to build the jobject.")
    lines.append(f"    {ret_stmt}")
    lines.append("}")

    return "\n".join(lines)


def generate_file(parsed: ParsedFile, source_name: str) -> str:
    struct_block = generate_all_struct_blocks(parsed)

    parts = [_FILE_HEADER.format(source=source_name)]
    if struct_block:
        parts.append(struct_block)
    for func in parsed.functions:
        try:
            body = generate_function(parsed, func)
        except UnknownTypeError as exc:
            raise UnknownTypeError(f"line {func.line}, {func.name}(): {exc}") from exc
        parts.append("")
        parts.append(body)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def generate_test_file(parsed: ParsedFile, source_name: str) -> str:
    """Generate a compile-time type-check file for helpers used by *source_name*."""
    known_enums = parsed.enum_names
    known_structs = parsed.struct_types

    basename = source_name.replace(".kt", "_jni_test.gen.cpp")
    lines: list[str] = [_TEST_FILE_HEADER.format(source=source_name, basename=basename)]

    fn_name = f"_compile_check_{parsed.class_name}"
    lines.append(f"static void {fn_name}(JNIEnv* env) {{")

    for func in parsed.functions:
        lines.append(f"    // {func.name}")
        lines.append("    if (false) {")

        for p in func.params:
            base = p.kotlin_type.rstrip("?").strip()
            if base in known_structs:
                lines.append(f"        jobject {p.name} = nullptr;")
                lines.append(f"        JNI_{base} {p.name}_val = extract_{base}(env, {p.name});")
                continue
            info = map_param_type(p.kotlin_type, known_enums, parsed.typealiases)
            if info.convert is None:
                continue
            zero = _JNI_ZERO.get(info.jni_type, "0")
            var = _cpp_var_name(p, info)
            lines.append(f"        {info.jni_type} {p.name} = {zero};")
            lines.append(
                f"        {info.cpp_type} {var} = {info.convert.format(env='env', var=p.name)};"
            )

        base_rt = func.return_type.rstrip("?").strip() if func.return_type else None
        if base_rt and base_rt in known_structs:
            lines.append(f"        JNI_{base_rt} _ret_struct{{}};")
            lines.append(f"        jobject _ret = make_{base_rt}(env, _ret_struct);")
        else:
            entry = _MAKE_HELPER_MAP.get(base_rt or "")
            if entry:
                make_fn, cpp_type = entry
                lines.append(f"        {cpp_type} _ret_val{{}};")
                lines.append(f"        jobject _ret = {make_fn}(env, _ret_val);")

        lines.append("    }")

    lines.append("}")
    lines.append("")
    lines.append("int main() { return 0; }")
    lines.append("")
    return "\n".join(lines)


def output_basename(parsed: ParsedFile, qualified: bool) -> str:
    if qualified and parsed.package:
        prefix = parsed.package.replace(".", "_") + "_"
        return f"{prefix}{parsed.class_name}_jni.gen.cpp"
    return f"{parsed.class_name}_jni.gen.cpp"


def test_output_basename(parsed: ParsedFile, qualified: bool) -> str:
    if qualified and parsed.package:
        prefix = parsed.package.replace(".", "_") + "_"
        return f"{prefix}{parsed.class_name}_jni_test.gen.cpp"
    return f"{parsed.class_name}_jni_test.gen.cpp"
