/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
import com.awakekt.awake.build.extension.*
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("com.awakekt.awake.plugin.publish")
    id("com.awakekt.awake.plugin.dokka")
    id("com.awakekt.awake.plugin.detekt")
    id("com.awakekt.awake.plugin.backend-layering")
    id("com.awakekt.awake.plugin.spotless")
}

kotlin {
    // 25, not the repo-wide 17: wgpu4k-jvm ships bytecode built for JVM target 25, and Kotlin
    // refuses to inline a 25-target inline function into a 17-target caller. Contained to this
    // module -- its desktop target is test-only (nothing consumes its desktop output), and the
    // wasmJs target this backend actually ships is unaffected. Auto-provisioned via the foojay
    // resolver in settings.gradle.kts.
    jvmToolchain(25)

    // Module restructuring slice 2 (see docs/mvp-plan.md): physically split out of
    // awake-vulkan (now awake-backend-vulkan). wasmJs is the only target this backend SHIPS to
    // -- production runs Vulkan on desktop/Android (decision-log D26).
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    // Desktop is a TEST target, not a shipping one. wgpu4k publishes a jvm variant and
    // wgpu4k-native-jvm bundles prebuilt libwgpu_native binaries, so this backend can run
    // headless on the JVM and reuse the pixel-baseline harness -- WebGPU was otherwise
    // compile-checked and never pixel-checked. It exercises Awake's WebGPU code path over
    // wgpu-native, NOT a browser's WebGPU implementation, so canvas sizing, JS interop and
    // browser driver quirks still need a browser check.
    jvm("desktop")

    // GLFW (which wgpu4k's desktop context bootstrap uses) refuses to initialise off the
    // process's first thread on macOS. Harmless elsewhere -- the flag only exists on the macOS
    // JVM, so it is applied per-host rather than unconditionally.
    if (HostOs.isMac) {
        tasks.withType<Test>().configureEach {
            jvmArgs(
                "-XstartOnFirstThread",
                // wgpu4k reaches the CAMetalLayer through Rococoa, whose cglib needs to
                // defineClass into java.lang -- JPMS blocks that by default on a modern JDK.
                "--add-opens", "java.base/java.lang=ALL-UNNAMED",
            )
        }
    }

    // This module's tests open a real wgpu device, so they contend for the adapter with every
    // other module that opens one. Every such module already took the shared token except this
    // one -- which is how `awake:backend:vulkan`'s tests could still meet a device that refuses
    // to open while running beside these.
    tasks.withType<Test>().configureEach { requireExclusiveGpu(this) }

    // detekt's compiler frontend tops out at JVM target 22, and this module's toolchain is 25
    // (see jvmToolchain above). The target only affects detekt's own analysis, not the bytecode
    // this module produces, so pinning it back is safe.
    tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
        jvmTarget = "22"
    }
    tasks.withType<io.gitlab.arturbosch.detekt.DetektCreateBaselineTask>().configureEach {
        jvmTarget = "22"
    }

    sourceSets {
        commonMain.dependencies {
            api(project(":awake:engine:render:passes2d"))
            implementation(project(":awake:core:graphics2d"))
            implementation(project(":awake:core:math2d"))
            implementation(project(":awake:core:color"))
            implementation(project(":awake:core:host"))
            implementation(project(":awake:core:input"))
            implementation(project(":awake:core:math"))
            implementation(project(":awake:core:text"))
            // Mesh/Material/Renderer implement the same narrow backend-neutral interfaces
            // awake-backend-vulkan's do -- see awake-engine-render-api's module doc.
            api(project(":awake:engine:render:contract"))
            // The shared render-pass layer (SharedOpaqueRenderFeature + the CommandRecorder
            // port). `api`, not `implementation`: this module's public pipeline/mesh/material
            // types implement the port's handle interfaces, so consumers see them.
            api(project(":awake:engine:render:passes"))
            // ShaderSet/ShaderStages/ShaderSource -- api, not implementation: WebGpuEngine's own
            // public constructor takes ShaderSet params, so a consumer needs the type visible
            // too (matches awake-backend-vulkan's identical api(awake:asset:shaders) dependency).
            api(project(":awake:asset:shaders"))
            // Built-in UI/debug shader artifacts are generated by the shader pack. Keeping this
            // dependency on the production classpath makes ASL-generated WGSL available to the
            // same runtime resource lookup used by Vulkan.
            implementation(project(":awake:asset:shader-pack"))
            // HeadlessRenderSession, the shape both backends hand a windowless renderer back in.
            api(project(":awake:engine:render:testing"))
            implementation(libs.kotlinx.coroutines.core)
            // Multiplatform: the same wgpu4k API backs both wasmJs and the desktop test target.
            // Only the toolkit (canvas bootstrap) and kotlinx-browser stay wasm-only.
            implementation(libs.wgpu4k)
            implementation(libs.webgpu.ktypes.descriptors)
            // Toolkit, not just core: `WGPUContext` is the device/surface bundle GraphicsDevice
            // takes, and it is published for BOTH wasmJs and jvm. Only the bootstrap that
            // produces one differs -- canvasContextRenderer() on wasm, glfwContextRenderer() on
            // desktop -- so no abstraction over it is needed here.
            implementation(libs.wgpu4k.toolkit)
            // WebGpuGameApplication now extends GameApplication (see
            // docs/reference/decision-log.md for the duplication this replaces). `api`,
            // not `implementation`: same reasoning as awake-backend-vulkan's identical
            // dependency -- it's a supertype, so consumers need it on their classpath too.
            api(project(":awake:engine:platform"))
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(project(":awake:engine:compose"))
        }
        // The desktop TEST target reads the same .wgsl this backend ships to wasm -- UI and
        // debug-line shaders the Renderer's constructor requires. Pointed at the one existing
        // copy rather than duplicated, so a shader edit cannot drift between the two.
        named("desktopTest") {
            resources.srcDir("src/wasmJsMain/resources")
            // lit_shadow.wgsl, for the shadow bind-group test. The shader pack's own synced
            // WebGPU copy, not a duplicate here: a copy would drift the moment the ASL
            // definition is re-recorded.
            resources.srcDir(
                project(":awake:asset:shader-pack").file("src/wasmJsMain/resources"),
            )
        }

        named("wasmJsMain") {
            dependencies {
                implementation(libs.kotlinx.browser)
            }
        }
    }
}

mavenPublishing {
    pom {
        name.set("Awake WebGPU Backend")
        description.set("The WebGPU renderer for browser and desktop targets, running WGSL natively")
    }
}
