/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.awakekt.awake.lucide.icon

import com.awakekt.awake.compose.ui.graphics.vector.ImageVector
import com.awakekt.awake.compose.ui.graphics.vector.imageVector
import com.awakekt.awake.core.graphics2d.UiFillRule
import com.awakekt.awake.core.graphics2d.UiStroke
import com.awakekt.awake.core.graphics2d.UiStrokeCap
import com.awakekt.awake.core.graphics2d.UiStrokeJoin
import com.awakekt.awake.core.math2d.dp

/**
 * [Lucide](https://lucide.dev) vector paths generated from the published SVG sources.
 *
 * This is raw, unbranded vector data. Recipes select it through their own registry so a design
 * system can replace the glyph family without copying or changing the source paths.
 */
object LucideIcons {
    /** Lucide camera (0.469.0, picosvg stroke expansion), generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val camera: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path {
            moveTo(14.5f, 3f)
            quadTo(14.968f, 3f, 15.268f, 3.36f)
            lineTo(17.468f, 6f)
            lineTo(20f, 6f)
            quadTo(23f, 6f, 23f, 9f)
            lineTo(23f, 18f)
            quadTo(23f, 21f, 20f, 21f)
            lineTo(4f, 21f)
            quadTo(1f, 21f, 1f, 18f)
            lineTo(1f, 9f)
            quadTo(1f, 6f, 4f, 6f)
            lineTo(6.532f, 6f)
            lineTo(8.732f, 3.36f)
            quadTo(9.032f, 3f, 9.5f, 3f)
            close()
            moveTo(14.032f, 5f)
            lineTo(9.968f, 5f)
            lineTo(7.768f, 7.64f)
            quadTo(7.468f, 8f, 7f, 8f)
            lineTo(4f, 8f)
            quadTo(3f, 8f, 3f, 9f)
            lineTo(3f, 18f)
            quadTo(3f, 19f, 4f, 19f)
            lineTo(20f, 19f)
            quadTo(21f, 19f, 21f, 18f)
            lineTo(21f, 9f)
            quadTo(21f, 8f, 20f, 8f)
            lineTo(17f, 8f)
            quadTo(16.532f, 8f, 16.232f, 7.64f)
            lineTo(14.032f, 5f)
            close()
        }
        path {
            moveTo(16f, 13f)
            quadTo(16f, 17f, 12f, 17f)
            quadTo(8f, 17f, 8f, 13f)
            quadTo(8f, 9f, 12f, 9f)
            quadTo(16f, 9f, 16f, 13f)
            close()
            moveTo(14f, 13f)
            quadTo(14f, 11f, 12f, 11f)
            quadTo(10f, 11f, 10f, 13f)
            quadTo(10f, 15f, 12f, 15f)
            quadTo(14f, 15f, 14f, 13f)
            close()
        }
    }

    /** Lucide check (0.469.0), generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val check: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(20f, 6f)
            lineTo(9f, 17f)
            lineTo(4f, 12f)
        }
    }

    /** Lucide chevron-down (0.469.0), generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val chevronDown: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(6f, 9f)
            lineTo(12f, 15f)
            lineTo(18f, 9f)
        }
    }

    /** Lucide chevron-up (0.469.0), generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val chevronUp: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(18f, 15f)
            lineTo(12f, 9f)
            lineTo(6f, 15f)
        }
    }

    /** Lucide gallery-vertical-end (0.469.0), stroke-expanded via picosvg, generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val galleryVerticalEnd: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path {
            moveTo(7f, 1f)
            lineTo(17f, 1f)
            quadTo(17.414f, 1f, 17.707f, 1.293f)
            quadTo(18f, 1.586f, 18f, 2f)
            quadTo(18f, 2.414f, 17.707f, 2.707f)
            quadTo(17.414f, 3f, 17f, 3f)
            lineTo(7f, 3f)
            quadTo(6.586f, 3f, 6.293f, 2.707f)
            quadTo(6f, 2.414f, 6f, 2f)
            quadTo(6f, 1.586f, 6.293f, 1.293f)
            quadTo(6.586f, 1f, 7f, 1f)
            close()
        }
        path {
            moveTo(5f, 5f)
            lineTo(19f, 5f)
            quadTo(19.414f, 5f, 19.707f, 5.293f)
            quadTo(20f, 5.586f, 20f, 6f)
            quadTo(20f, 6.414f, 19.707f, 6.707f)
            quadTo(19.414f, 7f, 19f, 7f)
            lineTo(5f, 7f)
            quadTo(4.586f, 7f, 4.293f, 6.707f)
            quadTo(4f, 6.414f, 4f, 6f)
            quadTo(4f, 5.586f, 4.293f, 5.293f)
            quadTo(4.586f, 5f, 5f, 5f)
            close()
        }
        path(fillRule = UiFillRule.EvenOdd) {
            moveTo(5f, 9f)
            lineTo(19f, 9f)
            quadTo(22f, 9f, 22f, 12f)
            lineTo(22f, 20f)
            quadTo(22f, 23f, 19f, 23f)
            lineTo(5f, 23f)
            quadTo(2f, 23f, 2f, 20f)
            lineTo(2f, 12f)
            quadTo(2f, 9f, 5f, 9f)
            close()
            moveTo(5f, 11f)
            quadTo(4f, 11f, 4f, 12f)
            lineTo(4f, 20f)
            quadTo(4f, 21f, 5f, 21f)
            lineTo(19f, 21f)
            quadTo(20f, 21f, 20f, 20f)
            lineTo(20f, 12f)
            quadTo(20f, 11f, 19f, 11f)
            close()
        }
    }

    /** Lucide chevron-right (0.469.0), generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val chevronRight: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(9f, 18f)
            lineTo(15f, 12f)
            lineTo(9f, 6f)
        }
    }

    /** Lucide chevrons-up-down (0.469.0), generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val chevronsUpDown: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(7f, 15f)
            lineTo(12f, 20f)
            lineTo(17f, 15f)
        }
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(7f, 9f)
            lineTo(12f, 4f)
            lineTo(17f, 9f)
        }
    }

    /** Lucide save (0.469.0), generated by skills/awake-ui-icons/scripts/svg_to_ui_image_vector.py -- do not hand-edit. */
    val save: ImageVector = imageVector(
        defaultWidth = 16f.dp,
        defaultHeight = 16f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ) {
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(15.2f, 3f)
            cubicTo(15.7275f, 3.0075f, 16.2307f, 3.2232f, 16.6f, 3.6f)
            lineTo(20.4f, 7.4f)
            cubicTo(20.7768f, 7.7693f, 20.9925f, 8.2725f, 21f, 8.8f)
            lineTo(21f, 19f)
            cubicTo(21f, 20.1046f, 20.1046f, 21f, 19f, 21f)
            lineTo(5f, 21f)
            cubicTo(3.8954f, 21f, 3f, 20.1046f, 3f, 19f)
            lineTo(3f, 5f)
            cubicTo(3f, 3.8954f, 3.8954f, 3f, 5f, 3f)
            close()
        }
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(17f, 21f)
            lineTo(17f, 14f)
            cubicTo(17f, 13.4477f, 16.5523f, 13f, 16f, 13f)
            lineTo(8f, 13f)
            cubicTo(7.4477f, 13f, 7f, 13.4477f, 7f, 14f)
            lineTo(7f, 21f)
        }
        path(stroke = UiStroke(width = 2f.dp, cap = UiStrokeCap.Round, join = UiStrokeJoin.Round)) {
            moveTo(7f, 3f)
            lineTo(7f, 7f)
            cubicTo(7f, 7.5523f, 7.4477f, 8f, 8f, 8f)
            lineTo(15f, 8f)
        }
    }
}
