// Copyright (c) Ron June Valdoz
// SPDX-License-Identifier: Apache-2.0
package io.github.ronjunevaldoz.awake.ecs

import kotlin.reflect.KClass

/**
 * Creates a platform-optimized array for component storage.
 */
internal expect fun <T : Any> newComponentArray(type: KClass<T>, capacity: Int): Array<Any?>

/**
 * Creates a new instance of [type]. Platform dependent.
 */
internal expect fun <T : Any> createComponentInstance(type: KClass<T>): T

/**
 * A cheap, platform-specific identity token for reified [T], used to key [ComponentRegistry]'s
 * type-id lookups from `World`'s reified `add`/`remove`/`get`/`has` sugar without paying for a
 * fresh `KClass` wrapper allocation on every call. Without `kotlin-reflect` on the classpath,
 * plain `T::class` inside a reified inline function re-derives a `kotlin.jvm.internal
 * .ClassReference` via `Reflection.getOrCreateKotlinClass` on *every single call* -- there is no
 * per-call-site caching the way a literal, non-reified `SomeClass::class` gets, since the
 * reification happens by textual substitution at each call site (confirmed by decompiling a
 * reified inline function's generated bytecode: `Reflection.getOrCreateKotlinClass` shows up
 * inside the loop body itself, not hoisted out). On the JVM/Android this is fixed by the actual
 * implementation using the `reified T -> T::class.java` idiom specifically, which the Kotlin
 * compiler recognizes and compiles directly to an `LDC <Class>` constant load, entirely bypassing
 * `Reflection.getOrCreateKotlinClass` (verified the same way). See
 * [componentTypeKeyOf] for the non-reified counterpart used when a `KClass` is already in hand.
 */
@PublishedApi
internal expect inline fun <reified T : Any> componentTypeKey(): Any

/**
 * Derives the same key [componentTypeKey] would produce for [type], for callers that already
 * have a resolved `KClass` (so no reified type parameter, and no reflection cost either --
 * `KClass.java` is a plain property read on an already-constructed wrapper).
 */
internal expect fun <T : Any> componentTypeKeyOf(type: KClass<T>): Any
