/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.awakekt.awake.asset.shaderdsl

internal enum class AslStage { Vertex, Fragment }

/** Deterministic WGSL text from a validated definition: consts, uniform blocks, texture
 * bindings, varyings struct, functions, vertex, fragment -- 2-space indent, minimal
 * parentheses, stable ordering, so the committed output diffs cleanly and naga sees the same
 * bytes on every platform. */
internal class WgslEmitter(private val definition: AslShaderDefinition) {

    fun emit(): String = buildString {
        appendLine("// Generated by Awake Lab ASL (:awake:asset:shader-dsl) -- shader '${definition.name}'.")
        appendLine("// Do not edit: change the Kotlin definition, re-record with AWAKE_RECORD_SHADERS=1.")
        appendLine("// Deliberately undated so record runs are byte-reproducible.")
        appendLine()
        definition.consts.forEach {
            appendLine(
                "const ${it.name} : ${wgslTypeName(it.value.type)} = ${render(it.value, AslStage.Fragment)};",
            )
        }
        if (definition.consts.isNotEmpty()) appendLine()
        definition.uniformBlocks.forEach { appendUniformBlock(it) }
        definition.textures.forEach {
            appendLine("@binding(${it.binding}) @group(${it.group}) var ${it.name} : ${wgslTypeName(it.type)};")
        }
        if (definition.textures.isNotEmpty()) appendLine()
        definition.storageBindings.forEach { appendStorage(it) }
        definition.varyings?.let { appendVaryings(it) }
        definition.functions.forEach { appendFunction(it) }
        appendVertex()
        appendFragment()
    }

    private fun StringBuilder.appendUniformBlock(block: AslUniformBlock) {
        appendLine("struct ${block.structName} {")
        block.fields.forEach {
            val type = if (it.count > 1) {
                "array<${wgslTypeName(it.type)}, ${it.count}>"
            } else {
                wgslTypeName(it.type)
            }
            appendLine("  ${it.name} : $type,")
        }
        appendLine("}")
        appendLine(
            "@binding(${block.binding}) @group(${block.group}) " +
                "var<uniform> ${block.instanceName} : ${block.structName};",
        )
        appendLine()
    }

    private fun StringBuilder.appendStorage(storage: AslStorageBinding) {
        appendLine("struct ${storage.structName} {")
        appendLine("  ${storage.fieldName} : array<${wgslType(storage.elementShape)}, ${storage.elementCount}>,")
        appendLine("}")
        appendLine(
            "@binding(${storage.binding}) @group(${storage.group}) " +
                "var<storage, read> ${storage.varName} : array<${storage.structName}>;",
        )
        appendLine()
    }

    private fun StringBuilder.appendVaryings(varyings: AslVaryings) {
        appendLine("struct ${varyings.structName} {")
        appendLine("  @builtin(position) position : vec4f,")
        varyings.fields.sortedBy { it.location }.forEach {
            appendLine("  @location(${it.location}) ${it.name} : ${wgslType(it.shape)},")
        }
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendFunction(function: AslFunctionDef) {
        val params = function.params.joinToString { "${it.name} : ${wgslTypeName(it.type)}" }
        appendLine("fn ${function.name}($params) -> ${wgslTypeName(function.returnType)} {")
        appendStatements(function.body, AslStage.Fragment, 1)
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendVertex() {
        val stage = definition.vertexStage
        val builtins = buildList {
            if (stage.usesInstanceIndex) add("@builtin(instance_index) instanceIndex : u32")
            if (stage.usesVertexIndex) add("@builtin(vertex_index) vertexIndex : u32")
        }
        val params = builtins + stage.inputs.sortedBy { it.location }
            .map { "@location(${it.location}) ${it.name} : ${wgslType(it.shape)}" }
        val returnType = definition.varyings?.structName ?: "@builtin(position) vec4f"
        appendLine("@vertex")
        if (params.size <= 2) {
            appendLine("fn ${stage.entryPoint}(${params.joinToString()}) -> $returnType {")
        } else {
            appendLine("fn ${stage.entryPoint}(")
            params.forEach { appendLine("  $it,") }
            appendLine(") -> $returnType {")
        }
        if (stage.positionOnly != null) {
            appendStatements(stage.statements, AslStage.Vertex, 1)
            appendLine("  return ${render(stage.positionOnly, AslStage.Vertex)};")
        } else {
            appendLine("  var output : ${definition.varyings?.structName};")
            appendStatements(stage.statements, AslStage.Vertex, 1)
            appendLine("  return output;")
        }
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendFragment() {
        val stage = definition.fragmentStage
        val varyingParams = definition.varyings?.fields.orEmpty().sortedBy { it.location }
            .map { "@location(${it.location}) ${it.name} : ${wgslType(it.shape)}" }
        val params = buildList {
            if (stage.usesPosition) add("@builtin(position) position : vec4f")
            addAll(varyingParams)
        }
        appendLine("@fragment")
        val returnType = if (stage.returnValue != null) " -> @location(0) vec4f" else ""
        if (params.size <= 2) {
            appendLine("fn ${stage.entryPoint}(${params.joinToString()})$returnType {")
        } else {
            appendLine("fn ${stage.entryPoint}(")
            params.forEach { appendLine("  $it,") }
            appendLine(")$returnType {")
        }
        appendStatements(stage.statements, AslStage.Fragment, 1)
        stage.returnValue?.let { appendLine("  return ${render(it, AslStage.Fragment)};") }
        appendLine("}")
    }

    private fun StringBuilder.appendStatements(statements: List<AslStatement>, stage: AslStage, depth: Int) {
        statements.forEach { appendStatement(it, stage, depth) }
    }

    private fun StringBuilder.appendStatement(statement: AslStatement, stage: AslStage, depth: Int) {
        val pad = "  ".repeat(depth)
        when (statement) {
            is AslAssign ->
                appendLine("$pad${render(statement.target, stage)} = ${render(statement.value, stage)};")
            is AslLet -> appendLine("${pad}let ${statement.name} = ${render(statement.value, stage)};")
            is AslVar -> appendLine("${pad}var ${statement.name} = ${render(statement.value, stage)};")
            is AslSet -> appendLine("$pad${statement.name} = ${render(statement.value, stage)};")
            is AslIf -> appendIf(statement, stage, depth)
            is AslForI32 -> {
                val c = statement.counter
                appendLine(
                    "${pad}for (var $c = ${render(statement.start, stage)}; " +
                        "$c <= ${render(statement.endInclusive, stage)}; $c = $c + 1) {",
                )
                appendStatements(statement.body, stage, depth + 1)
                appendLine("$pad}")
            }
            is AslForU32 -> {
                val c = statement.counter
                appendLine(
                    "${pad}for (var $c = ${render(statement.start, stage)}; " +
                        "$c < ${render(statement.endExclusive, stage)}; $c = $c + 1u) {",
                )
                appendStatements(statement.body, stage, depth + 1)
                appendLine("$pad}")
            }
            is AslReturn -> {
                val value = statement.value?.let { " ${render(it, stage)}" } ?: ""
                appendLine("${pad}return$value;")
            }
            AslContinue -> appendLine("${pad}continue;")
            AslDiscard -> appendLine("${pad}discard;")
        }
    }

    /** Single `continue`/`return` bodies inline to one line, matching the hand-written
     * `if (slot.w <= 0.0) { continue; }` shape; anything else opens a block. */
    private fun StringBuilder.appendIf(statement: AslIf, stage: AslStage, depth: Int) {
        val pad = "  ".repeat(depth)
        val condition = render(statement.condition, stage)
        val only = statement.body.singleOrNull()
        if (only is AslContinue) {
            appendLine("${pad}if ($condition) { continue; }")
        } else if (only is AslReturn && only.value != null) {
            appendLine("${pad}if ($condition) {")
            appendLine("$pad  return ${render(only.value, stage)};")
            appendLine("$pad}")
        } else {
            appendLine("${pad}if ($condition) {")
            appendStatements(statement.body, stage, depth + 1)
            appendLine("$pad}")
        }
    }
}
