/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.awakekt.awake.scene.rendering

import com.awakekt.awake.ecs.World
import com.awakekt.awake.render.passes.RenderDrawCommand
import com.awakekt.awake.render.passes.uniforms.EnvironmentUniforms
import com.awakekt.awake.render.passes.uniforms.SceneLight

/** Backend-neutral scene feature extension point owned by [RenderSystem3D]. */
interface RenderFeature3D {
    /**
     * Collects render contributions from the given ECS [world] for this frame.
     *
     * @param world The active ECS world containing scene entities.
     * @param context Read-only frame context containing camera and timing inputs.
     * @return The collected [RenderContribution] describing draw commands and lighting.
     */
    fun collect(world: World, context: RenderFeatureContext3D): RenderContribution
}

/**
 * Read-only frame inputs exposed to a scene feature.
 *
 * @property camera The active primary scene camera.
 * @property elapsedTimeSeconds Total elapsed simulation time in seconds.
 * @property viewportAspect Viewport aspect ratio (width / height).
 */
data class RenderFeatureContext3D(
    val camera: Camera,
    val elapsedTimeSeconds: Float,
    val viewportAspect: Float,
) {
    /** Keeps the original two-argument constructor for existing feature implementations. */
    constructor(camera: Camera, elapsedTimeSeconds: Float) : this(camera, elapsedTimeSeconds, 16f / 9f)

    /** Keeps the original data-class copy shape and preserves the frame's viewport aspect. */
    fun copy(
        camera: Camera = this.camera,
        elapsedTimeSeconds: Float = this.elapsedTimeSeconds,
    ): RenderFeatureContext3D = RenderFeatureContext3D(camera, elapsedTimeSeconds, viewportAspect)
}

/**
 * Data a feature contributes; GPU submission remains owned by [RenderSystem3D].
 *
 * @property draws Draw commands generated by the feature for this frame.
 * @property light Optional lighting contribution evaluated for the frame.
 * @property environment Optional environment uniforms (fog, ambient, sky) for the frame.
 */
data class RenderContribution(
    val draws: List<RenderDrawCommand> = emptyList(),
    val light: SceneLight? = null,
    val environment: EnvironmentUniforms? = null,
)

/** Built-in lighting feature; it reads scene state and returns only generic render inputs. */
internal class SceneLightingFeature3D(
    private val compiler: SceneLightingCompiler,
) : RenderFeature3D {
    override fun collect(world: World, context: RenderFeatureContext3D): RenderContribution =
        RenderContribution(
            light = compiler.sceneLight(world, context.camera, context.viewportAspect),
            environment = compiler.environmentUniforms(world),
        )
}

/** Built-in particle feature; its contribution is inserted between opaque and LOD families. */
internal class SceneParticleFeature3D(
    private val compiler: SceneParticleCompiler,
) : RenderFeature3D {
    override fun collect(world: World, context: RenderFeatureContext3D): RenderContribution {
        val draws = ArrayList<RenderDrawCommand>()
        compiler.appendWorldDrawCalls(draws, world, context.camera, context.viewportAspect)
        return RenderContribution(draws = draws)
    }
}
