// Copyright (c) Ron June Valdoz
// SPDX-License-Identifier: Apache-2.0
package io.github.ronjunevaldoz.awake.ui.unstyled

import io.github.ronjunevaldoz.awake.ui.UiFillRule
import io.github.ronjunevaldoz.awake.ui.UiImageVector
import io.github.ronjunevaldoz.awake.ui.UiStroke
import io.github.ronjunevaldoz.awake.ui.UiStrokeCap
import io.github.ronjunevaldoz.awake.ui.UiStrokeJoin
import io.github.ronjunevaldoz.awake.ui.dp
import io.github.ronjunevaldoz.awake.ui.uiImageVector

/** [Heroicons](https://heroicons.com) vector paths, generated from the published SVG sources by
 * `tools/svg_to_ui_image_vector.py` with curves preserved as real cubic Beziers and holes kept
 * as `UiFillRule.EvenOdd` contours. Never hand-edit or hand-transcribe path data here -- re-run
 * the generator instead (see `skills/awake-icon-authoring/SKILL.md`). Grows one glyph at a
 * time, on demand.
 *
 * Nested one object per real Heroicons style+size tier, not a flat glyph list -- Heroicons ships
 * genuinely different path data per tier (24px solid, 20px "mini" solid, 16px "micro" solid), so
 * there is no single correct [UiImageVector] per glyph name. [Solid20Mini] is the only tier
 * generated so far; add further tiers only when an icon actually needs one.
 *
 * [Outline24] carries Heroicons' `24/outline` tier -- stroke-only source SVGs converted at draw
 * time to an equivalent filled outline (`strokeToFillPath` in ui-core's `UiPath.kt`; `icon()` in
 * ui-headless's `Icon.kt` calls it when a [UiVectorPath][io.github.ronjunevaldoz.awake.ui
 * .UiVectorPath] carries a `stroke`), never pre-flattened into path data here.
 *
 * A generic, unbranded home for icon vector data -- [io.github.ronjunevaldoz.awake.ui.designsystem
 * .components.ShadcnIcons] is the shadcn-facing, *overridable* pointer registry that defaults to
 * these but doesn't have to stay pinned to them; a caller wanting a different icon set entirely
 * reassigns `ShadcnIcons.xxx` without this object needing to know or care. */
object HeroIcons {
    /** Heroicons' `solid/20/solid` tier ("mini") -- the size real shadcn/ui's own chrome
     * (dropdown/collapsible chevrons, small inline affordances) actually uses. */
    object Solid20Mini {
        /** Heroicons `chevron-down` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        /** Heroicons x-mark (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val xMark: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(6.28f, 5.22f)
                cubicTo(5.9845f, 4.9446f, 5.524f, 4.9528f, 5.2384f, 5.2384f)
                cubicTo(4.9528f, 5.524f, 4.9446f, 5.9845f, 5.22f, 6.28f)
                lineTo(8.94f, 10f)
                lineTo(5.22f, 13.72f)
                cubicTo(5.0193f, 13.907f, 4.9368f, 14.1886f, 5.0046f, 14.4543f)
                cubicTo(5.0725f, 14.72f, 5.28f, 14.9275f, 5.5457f, 14.9954f)
                cubicTo(5.8114f, 15.0632f, 6.093f, 14.9807f, 6.28f, 14.78f)
                lineTo(10f, 11.06f)
                lineTo(13.72f, 14.78f)
                cubicTo(13.907f, 14.9807f, 14.1886f, 15.0632f, 14.4543f, 14.9954f)
                cubicTo(14.72f, 14.9275f, 14.9275f, 14.72f, 14.9954f, 14.4543f)
                cubicTo(15.0632f, 14.1886f, 14.9807f, 13.907f, 14.78f, 13.72f)
                lineTo(11.06f, 10f)
                lineTo(14.78f, 6.28f)
                cubicTo(15.0554f, 5.9845f, 15.0472f, 5.524f, 14.7616f, 5.2384f)
                cubicTo(14.476f, 4.9528f, 14.0155f, 4.9446f, 13.72f, 5.22f)
                lineTo(10f, 8.94f)
                lineTo(6.28f, 5.22f)
                close()
            }
        }

        val chevronDown: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(5.22f, 8.22f)
                cubicTo(5.5128f, 7.9275f, 5.9872f, 7.9275f, 6.28f, 8.22f)
                lineTo(10f, 11.94f)
                lineTo(13.72f, 8.22f)
                cubicTo(13.907f, 8.0193f, 14.1886f, 7.9368f, 14.4543f, 8.0046f)
                cubicTo(14.72f, 8.0725f, 14.9275f, 8.28f, 14.9954f, 8.5457f)
                cubicTo(15.0632f, 8.8114f, 14.9807f, 9.093f, 14.78f, 9.28f)
                lineTo(10.53f, 13.53f)
                cubicTo(10.2372f, 13.8225f, 9.7628f, 13.8225f, 9.47f, 13.53f)
                lineTo(5.22f, 9.28f)
                cubicTo(4.9275f, 8.9872f, 4.9275f, 8.5128f, 5.22f, 8.22f)
                close()
            }
        }

        /** Heroicons `chevron-up` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val chevronUp: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(9.47f, 6.47f)
                cubicTo(9.7628f, 6.1775f, 10.2372f, 6.1775f, 10.53f, 6.47f)
                lineTo(14.78f, 10.72f)
                cubicTo(14.9807f, 10.907f, 15.0632f, 11.1886f, 14.9954f, 11.4543f)
                cubicTo(14.9275f, 11.72f, 14.72f, 11.9275f, 14.4543f, 11.9954f)
                cubicTo(14.1886f, 12.0632f, 13.907f, 11.9807f, 13.72f, 11.78f)
                lineTo(10f, 8.06f)
                lineTo(6.28f, 11.78f)
                cubicTo(5.9845f, 12.0554f, 5.524f, 12.0472f, 5.2384f, 11.7616f)
                cubicTo(4.9528f, 11.476f, 4.9446f, 11.0155f, 5.22f, 10.72f)
                lineTo(9.47f, 6.47f)
                close()
            }
        }

        /** Heroicons `chevron-right` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val chevronRight: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(8.22f, 5.22f)
                cubicTo(8.5128f, 4.9275f, 8.9872f, 4.9275f, 9.28f, 5.22f)
                lineTo(13.53f, 9.47f)
                cubicTo(13.8225f, 9.7628f, 13.8225f, 10.2372f, 13.53f, 10.53f)
                lineTo(9.28f, 14.78f)
                cubicTo(8.9845f, 15.0554f, 8.524f, 15.0472f, 8.2384f, 14.7616f)
                cubicTo(7.9528f, 14.476f, 7.9446f, 14.0155f, 8.22f, 13.72f)
                lineTo(11.94f, 10f)
                lineTo(8.22f, 6.28f)
                cubicTo(7.9275f, 5.9872f, 7.9275f, 5.5128f, 8.22f, 5.22f)
                close()
            }
        }

        /** Heroicons `chevron-left` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val chevronLeft: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(11.78f, 5.22f)
                cubicTo(12.0725f, 5.5128f, 12.0725f, 5.9872f, 11.78f, 6.28f)
                lineTo(8.06f, 10f)
                lineTo(11.78f, 13.72f)
                cubicTo(11.9807f, 13.907f, 12.0632f, 14.1886f, 11.9954f, 14.4543f)
                cubicTo(11.9275f, 14.72f, 11.72f, 14.9275f, 11.4543f, 14.9954f)
                cubicTo(11.1886f, 15.0632f, 10.907f, 14.9807f, 10.72f, 14.78f)
                lineTo(6.47f, 10.53f)
                cubicTo(6.1775f, 10.2372f, 6.1775f, 9.7628f, 6.47f, 9.47f)
                lineTo(10.72f, 5.22f)
                cubicTo(11.0128f, 4.9275f, 11.4872f, 4.9275f, 11.78f, 5.22f)
                close()
            }
        }

        /** Heroicons `squares-2x2` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val squares2x2: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(4.25f, 2f)
                cubicTo(3.0074f, 2f, 2f, 3.0074f, 2f, 4.25f)
                lineTo(2f, 6.75f)
                cubicTo(2f, 7.9926f, 3.0074f, 9f, 4.25f, 9f)
                lineTo(6.75f, 9f)
                cubicTo(7.9926f, 9f, 9f, 7.9926f, 9f, 6.75f)
                lineTo(9f, 4.25f)
                cubicTo(9f, 3.0074f, 7.9926f, 2f, 6.75f, 2f)
                lineTo(4.25f, 2f)
                close()
                moveTo(4.25f, 11f)
                cubicTo(3.0074f, 11f, 2f, 12.0074f, 2f, 13.25f)
                lineTo(2f, 15.75f)
                cubicTo(2f, 16.9926f, 3.0074f, 18f, 4.25f, 18f)
                lineTo(6.75f, 18f)
                cubicTo(7.9926f, 18f, 9f, 16.9926f, 9f, 15.75f)
                lineTo(9f, 13.25f)
                cubicTo(9f, 12.0074f, 7.9926f, 11f, 6.75f, 11f)
                lineTo(4.25f, 11f)
                close()
                moveTo(13.25f, 2f)
                cubicTo(12.0074f, 2f, 11f, 3.0074f, 11f, 4.25f)
                lineTo(11f, 6.75f)
                cubicTo(11f, 7.9926f, 12.0074f, 9f, 13.25f, 9f)
                lineTo(15.75f, 9f)
                cubicTo(16.9926f, 9f, 18f, 7.9926f, 18f, 6.75f)
                lineTo(18f, 4.25f)
                cubicTo(18f, 3.0074f, 16.9926f, 2f, 15.75f, 2f)
                lineTo(13.25f, 2f)
                close()
                moveTo(13.25f, 11f)
                cubicTo(12.0074f, 11f, 11f, 12.0074f, 11f, 13.25f)
                lineTo(11f, 15.75f)
                cubicTo(11f, 16.9926f, 12.0074f, 18f, 13.25f, 18f)
                lineTo(15.75f, 18f)
                cubicTo(16.9926f, 18f, 18f, 16.9926f, 18f, 15.75f)
                lineTo(18f, 13.25f)
                cubicTo(18f, 12.0074f, 16.9926f, 11f, 15.75f, 11f)
                lineTo(13.25f, 11f)
                close()
            }
        }

        /** Heroicons `square-3-stack-3d` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val square3Stack3d: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(3.196f, 12.87f)
                lineTo(2.371f, 13.353f)
                cubicTo(2.1414f, 13.4876f, 2.0003f, 13.7338f, 2.0003f, 14f)
                cubicTo(2.0003f, 14.2662f, 2.1414f, 14.5124f, 2.371f, 14.647f)
                lineTo(9.621f, 18.897f)
                cubicTo(9.8551f, 19.0341f, 10.1449f, 19.0341f, 10.379f, 18.897f)
                lineTo(17.629f, 14.647f)
                cubicTo(17.8586f, 14.5124f, 17.9997f, 14.2662f, 17.9997f, 14f)
                cubicTo(17.9997f, 13.7338f, 17.8586f, 13.4876f, 17.629f, 13.353f)
                lineTo(16.804f, 12.869f)
                lineTo(11.138f, 16.191f)
                cubicTo(10.4353f, 16.603f, 9.5647f, 16.603f, 8.862f, 16.191f)
                lineTo(3.196f, 12.87f)
                close()
            }
            path {
                moveTo(3.196f, 8.87f)
                lineTo(2.371f, 9.353f)
                cubicTo(2.1414f, 9.4876f, 2.0003f, 9.7338f, 2.0003f, 10f)
                cubicTo(2.0003f, 10.2662f, 2.1414f, 10.5124f, 2.371f, 10.647f)
                lineTo(9.621f, 14.897f)
                cubicTo(9.8551f, 15.0341f, 10.1449f, 15.0341f, 10.379f, 14.897f)
                lineTo(17.629f, 10.647f)
                cubicTo(17.8586f, 10.5124f, 17.9997f, 10.2662f, 17.9997f, 10f)
                cubicTo(17.9997f, 9.7338f, 17.8586f, 9.4876f, 17.629f, 9.353f)
                lineTo(16.804f, 8.869f)
                lineTo(11.138f, 12.191f)
                cubicTo(10.4353f, 12.603f, 9.5647f, 12.603f, 8.862f, 12.191f)
                lineTo(3.196f, 8.87f)
                close()
            }
            path {
                moveTo(10.38f, 1.103f)
                cubicTo(10.1454f, 0.9651f, 9.8546f, 0.9651f, 9.62f, 1.103f)
                lineTo(2.37f, 5.353f)
                cubicTo(2.1404f, 5.4876f, 1.9993f, 5.7338f, 1.9993f, 6f)
                cubicTo(1.9993f, 6.2662f, 2.1404f, 6.5124f, 2.37f, 6.647f)
                lineTo(9.62f, 10.897f)
                cubicTo(9.8546f, 11.0349f, 10.1454f, 11.0349f, 10.38f, 10.897f)
                lineTo(17.63f, 6.647f)
                cubicTo(17.8596f, 6.5124f, 18.0007f, 6.2662f, 18.0007f, 6f)
                cubicTo(18.0007f, 5.7338f, 17.8596f, 5.4876f, 17.63f, 5.353f)
                lineTo(10.38f, 1.103f)
                close()
            }
        }

        /** Heroicons `table-cells` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val tableCells: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(0.99f, 5.24f)
                cubicTo(0.9926f, 4.6433f, 1.2322f, 4.072f, 1.6561f, 3.6519f)
                cubicTo(2.0799f, 3.2318f, 2.6533f, 2.9973f, 3.25f, 3f)
                lineTo(16.75f, 3f)
                cubicTo(17.9926f, 3f, 19f, 4.0074f, 19f, 5.25f)
                lineTo(19.01f, 14.75f)
                cubicTo(19.01f, 15.9926f, 18.0026f, 17f, 16.76f, 17f)
                lineTo(3.26f, 17f)
                cubicTo(2.0134f, 16.9962f, 1.0038f, 15.9866f, 1f, 14.74f)
                lineTo(0.99f, 5.24f)
                close()
                moveTo(9.25f, 14.76f)
                lineTo(9.25f, 14.135f)
                cubicTo(9.25f, 13.7208f, 8.9142f, 13.385f, 8.5f, 13.385f)
                lineTo(3.25f, 13.385f)
                cubicTo(2.8358f, 13.385f, 2.5f, 13.7208f, 2.5f, 14.135f)
                lineTo(2.5f, 14.75f)
                cubicTo(2.5f, 15.164f, 2.836f, 15.5f, 3.25f, 15.5f)
                lineTo(8.623f, 15.5f)
                cubicTo(8.9848f, 15.4398f, 9.2501f, 15.1268f, 9.25f, 14.76f)
                close()
                moveTo(10.75f, 14.76f)
                cubicTo(10.7499f, 15.1268f, 11.0152f, 15.4398f, 11.377f, 15.5f)
                lineTo(16.75f, 15.5f)
                cubicTo(17.1642f, 15.5f, 17.5f, 15.1642f, 17.5f, 14.75f)
                lineTo(17.5f, 14.135f)
                cubicTo(17.5f, 13.7208f, 17.1642f, 13.385f, 16.75f, 13.385f)
                lineTo(11.5f, 13.385f)
                cubicTo(11.0858f, 13.385f, 10.75f, 13.7208f, 10.75f, 14.135f)
                lineTo(10.75f, 14.76f)
                close()
                moveTo(17.5f, 11.13f)
                lineTo(17.5f, 10.505f)
                cubicTo(17.5f, 10.0908f, 17.1642f, 9.755f, 16.75f, 9.755f)
                lineTo(11.5f, 9.755f)
                cubicTo(11.0858f, 9.755f, 10.75f, 10.0908f, 10.75f, 10.505f)
                lineTo(10.75f, 11.13f)
                cubicTo(10.75f, 11.544f, 11.086f, 11.88f, 11.5f, 11.88f)
                lineTo(16.75f, 11.88f)
                cubicTo(17.1642f, 11.88f, 17.5f, 11.5442f, 17.5f, 11.13f)
                close()
                moveTo(9.25f, 11.13f)
                lineTo(9.25f, 10.505f)
                cubicTo(9.25f, 10.0908f, 8.9142f, 9.755f, 8.5f, 9.755f)
                lineTo(3.25f, 9.755f)
                cubicTo(2.8358f, 9.755f, 2.5f, 10.0908f, 2.5f, 10.505f)
                lineTo(2.5f, 11.13f)
                cubicTo(2.5f, 11.544f, 2.836f, 11.88f, 3.25f, 11.88f)
                lineTo(8.5f, 11.88f)
                cubicTo(8.9142f, 11.88f, 9.25f, 11.5442f, 9.25f, 11.13f)
                close()
                moveTo(17.5f, 7.5f)
                lineTo(17.5f, 6.875f)
                cubicTo(17.5f, 6.4608f, 17.1642f, 6.125f, 16.75f, 6.125f)
                lineTo(11.5f, 6.125f)
                cubicTo(11.0858f, 6.125f, 10.75f, 6.4608f, 10.75f, 6.875f)
                lineTo(10.75f, 7.5f)
                cubicTo(10.75f, 7.914f, 11.086f, 8.25f, 11.5f, 8.25f)
                lineTo(16.75f, 8.25f)
                cubicTo(17.1642f, 8.25f, 17.5f, 7.9142f, 17.5f, 7.5f)
                close()
                moveTo(9.25f, 7.5f)
                lineTo(9.25f, 6.875f)
                cubicTo(9.25f, 6.4608f, 8.9142f, 6.125f, 8.5f, 6.125f)
                lineTo(3.25f, 6.125f)
                cubicTo(2.8358f, 6.125f, 2.5f, 6.4608f, 2.5f, 6.875f)
                lineTo(2.5f, 7.5f)
                cubicTo(2.5f, 7.914f, 2.836f, 8.25f, 3.25f, 8.25f)
                lineTo(8.5f, 8.25f)
                cubicTo(8.9142f, 8.25f, 9.25f, 7.9142f, 9.25f, 7.5f)
                close()
            }
        }

        /** Heroicons `globe-alt` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val globeAlt: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(16.555f, 5.412f)
                cubicTo(15.6784f, 4.1612f, 14.4632f, 3.1864f, 13.052f, 2.602f)
                cubicTo(13.843f, 3.9937f, 14.4045f, 5.5037f, 14.715f, 7.074f)
                cubicTo(15.4059f, 6.6124f, 16.0257f, 6.0525f, 16.555f, 5.412f)
                close()
                moveTo(13.326f, 7.825f)
                cubicTo(12.9874f, 5.7375f, 12.1606f, 3.7595f, 10.913f, 2.052f)
                cubicTo(10.3063f, 1.9831f, 9.6937f, 1.9831f, 9.087f, 2.052f)
                cubicTo(7.8394f, 3.7595f, 7.0126f, 5.7375f, 6.674f, 7.825f)
                cubicTo(7.7258f, 8.272f, 8.8572f, 8.5016f, 10f, 8.5f)
                cubicTo(11.18f, 8.5f, 12.304f, 8.26f, 13.326f, 7.825f)
                close()
                moveTo(6.514f, 9.376f)
                cubicTo(7.6295f, 9.7902f, 8.8101f, 10.0015f, 10f, 10f)
                cubicTo(11.226f, 10f, 12.4f, 9.78f, 13.486f, 9.376f)
                cubicTo(13.5451f, 10.6392f, 13.427f, 11.9045f, 13.135f, 13.135f)
                cubicTo(12.1078f, 13.3785f, 11.0557f, 13.501f, 10f, 13.5f)
                cubicTo(8.921f, 13.5f, 7.872f, 13.373f, 6.866f, 13.134f)
                cubicTo(6.5738f, 11.9039f, 6.4553f, 10.639f, 6.514f, 9.376f)
                close()
                moveTo(5.285f, 7.074f)
                cubicTo(5.5956f, 5.504f, 6.1571f, 3.9944f, 6.948f, 2.603f)
                cubicTo(5.5368f, 3.1874f, 4.3216f, 4.1622f, 3.445f, 5.413f)
                cubicTo(3.974f, 6.051f, 4.594f, 6.612f, 5.285f, 7.073f)
                close()
                moveTo(17.334f, 6.798f)
                cubicTo(17.8993f, 8.0912f, 18.1111f, 9.5112f, 17.948f, 10.913f)
                cubicTo(16.9707f, 11.6265f, 15.9018f, 12.205f, 14.77f, 12.633f)
                cubicTo(15f, 11.3333f, 15.0585f, 10.009f, 14.944f, 8.694f)
                cubicTo(15.8326f, 8.1874f, 16.6385f, 7.548f, 17.334f, 6.798f)
                close()
                moveTo(2.666f, 6.798f)
                cubicTo(3.3615f, 7.548f, 4.1674f, 8.1874f, 5.056f, 8.694f)
                cubicTo(4.9426f, 10.0093f, 5.0011f, 11.3338f, 5.23f, 12.634f)
                cubicTo(4.0982f, 12.206f, 3.0293f, 11.6274f, 2.052f, 10.914f)
                cubicTo(1.8892f, 9.5121f, 2.1014f, 8.0921f, 2.667f, 6.799f)
                close()
                moveTo(10f, 15f)
                cubicTo(10.898f, 15f, 11.778f, 14.921f, 12.633f, 14.77f)
                cubicTo(12.205f, 15.9018f, 11.6264f, 16.9707f, 10.913f, 17.948f)
                cubicTo(10.3063f, 18.0168f, 9.6937f, 18.0168f, 9.087f, 17.948f)
                cubicTo(8.3735f, 16.9707f, 7.795f, 15.9018f, 7.367f, 14.77f)
                cubicTo(8.222f, 14.921f, 9.102f, 15f, 10f, 15f)
                close()
                moveTo(14.357f, 14.357f)
                cubicTo(14.0361f, 15.4156f, 13.5984f, 16.4352f, 13.052f, 17.397f)
                cubicTo(15.0193f, 16.5823f, 16.5823f, 15.0193f, 17.397f, 13.052f)
                cubicTo(16.444f, 13.594f, 15.426f, 14.033f, 14.357f, 14.357f)
                close()
                moveTo(6.948f, 17.397f)
                cubicTo(4.9807f, 16.5823f, 3.4177f, 15.0193f, 2.603f, 13.052f)
                cubicTo(3.556f, 13.594f, 4.574f, 14.033f, 5.643f, 14.357f)
                cubicTo(5.9639f, 15.4156f, 6.4016f, 16.4352f, 6.948f, 17.397f)
                close()
            }
        }

        /** Heroicons `clock` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val clock: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(10f, 18f)
                cubicTo(14.4183f, 18f, 18f, 14.4183f, 18f, 10f)
                cubicTo(18f, 5.5817f, 14.4183f, 2f, 10f, 2f)
                cubicTo(5.5817f, 2f, 2f, 5.5817f, 2f, 10f)
                cubicTo(2f, 14.4183f, 5.5817f, 18f, 10f, 18f)
                close()
                moveTo(10.75f, 5f)
                cubicTo(10.75f, 4.5858f, 10.4142f, 4.25f, 10f, 4.25f)
                cubicTo(9.5858f, 4.25f, 9.25f, 4.5858f, 9.25f, 5f)
                lineTo(9.25f, 10f)
                cubicTo(9.25f, 10.414f, 9.586f, 10.75f, 10f, 10.75f)
                lineTo(14f, 10.75f)
                cubicTo(14.4142f, 10.75f, 14.75f, 10.4142f, 14.75f, 10f)
                cubicTo(14.75f, 9.5858f, 14.4142f, 9.25f, 14f, 9.25f)
                lineTo(10.75f, 9.25f)
                lineTo(10.75f, 5f)
                close()
            }
        }

        /** Heroicons `arrow-path` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val arrowPath: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(15.312f, 11.424f)
                cubicTo(14.8034f, 13.3218f, 13.3211f, 14.8042f, 11.4233f, 15.3128f)
                cubicTo(9.5255f, 15.8214f, 7.5005f, 15.2791f, 6.111f, 13.89f)
                lineTo(5.799f, 13.579f)
                lineTo(8.232f, 13.579f)
                cubicTo(8.6462f, 13.579f, 8.982f, 13.2432f, 8.982f, 12.829f)
                cubicTo(8.982f, 12.4148f, 8.6462f, 12.079f, 8.232f, 12.079f)
                lineTo(3.989f, 12.079f)
                cubicTo(3.5748f, 12.079f, 3.239f, 12.4148f, 3.239f, 12.829f)
                lineTo(3.239f, 17.071f)
                cubicTo(3.239f, 17.4852f, 3.5748f, 17.821f, 3.989f, 17.821f)
                cubicTo(4.4032f, 17.821f, 4.739f, 17.4852f, 4.739f, 17.071f)
                lineTo(4.739f, 14.641f)
                lineTo(5.049f, 14.951f)
                cubicTo(6.8173f, 16.7198f, 9.3951f, 17.4107f, 11.811f, 16.7634f)
                cubicTo(14.2269f, 16.1161f, 16.1139f, 14.229f, 16.761f, 11.813f)
                cubicTo(16.8687f, 11.4129f, 16.6316f, 11.0012f, 16.2315f, 10.8935f)
                cubicTo(15.8314f, 10.7858f, 15.4197f, 11.0229f, 15.312f, 11.423f)
                close()
                moveTo(16.542f, 7.701f)
                cubicTo(16.6823f, 7.5603f, 16.7611f, 7.3697f, 16.761f, 7.171f)
                lineTo(16.761f, 2.929f)
                cubicTo(16.761f, 2.5148f, 16.4252f, 2.179f, 16.011f, 2.179f)
                cubicTo(15.5968f, 2.179f, 15.261f, 2.5148f, 15.261f, 2.929f)
                lineTo(15.261f, 5.36f)
                lineTo(14.951f, 5.05f)
                cubicTo(13.1827f, 3.2812f, 10.6049f, 2.5903f, 8.189f, 3.2376f)
                cubicTo(5.7731f, 3.8849f, 3.8861f, 5.772f, 3.239f, 8.188f)
                cubicTo(3.1603f, 8.4497f, 3.2302f, 8.7334f, 3.4214f, 8.9287f)
                cubicTo(3.6125f, 9.1239f, 3.8948f, 9.1997f, 4.158f, 9.1266f)
                cubicTo(4.4213f, 9.0534f, 4.624f, 8.8429f, 4.687f, 8.577f)
                cubicTo(5.1949f, 6.6782f, 6.6776f, 5.1948f, 8.5761f, 4.6859f)
                cubicTo(10.4746f, 4.177f, 12.5004f, 4.7199f, 13.89f, 6.11f)
                lineTo(14.201f, 6.42f)
                lineTo(11.769f, 6.42f)
                cubicTo(11.3548f, 6.42f, 11.019f, 6.7558f, 11.019f, 7.17f)
                cubicTo(11.019f, 7.5842f, 11.3548f, 7.92f, 11.769f, 7.92f)
                lineTo(16.012f, 7.92f)
                cubicTo(16.2107f, 7.9201f, 16.4013f, 7.8413f, 16.542f, 7.701f)
                close()
            }
        }

        /** Heroicons `camera` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val camera: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(1f, 8f)
                cubicTo(1f, 6.8954f, 1.8954f, 6f, 3f, 6f)
                lineTo(3.93f, 6f)
                cubicTo(4.5986f, 6.0001f, 5.223f, 5.6661f, 5.594f, 5.11f)
                lineTo(6.406f, 3.89f)
                cubicTo(6.777f, 3.3339f, 7.4014f, 2.9999f, 8.07f, 3f)
                lineTo(11.93f, 3f)
                cubicTo(12.5986f, 2.9999f, 13.223f, 3.3339f, 13.594f, 3.89f)
                lineTo(14.406f, 5.11f)
                cubicTo(14.777f, 5.6661f, 15.4014f, 6.0001f, 16.07f, 6f)
                lineTo(17f, 6f)
                cubicTo(18.1046f, 6f, 19f, 6.8954f, 19f, 8f)
                lineTo(19f, 15f)
                cubicTo(19f, 16.1046f, 18.1046f, 17f, 17f, 17f)
                lineTo(3f, 17f)
                cubicTo(1.8954f, 17f, 1f, 16.1046f, 1f, 15f)
                lineTo(1f, 8f)
                close()
                moveTo(14.5f, 11f)
                cubicTo(14.5f, 13.4853f, 12.4853f, 15.5f, 10f, 15.5f)
                cubicTo(7.5147f, 15.5f, 5.5f, 13.4853f, 5.5f, 11f)
                cubicTo(5.5f, 8.5147f, 7.5147f, 6.5f, 10f, 6.5f)
                cubicTo(12.4853f, 6.5f, 14.5f, 8.5147f, 14.5f, 11f)
                close()
                moveTo(10f, 14f)
                cubicTo(11.6569f, 14f, 13f, 12.6569f, 13f, 11f)
                cubicTo(13f, 9.3431f, 11.6569f, 8f, 10f, 8f)
                cubicTo(8.3431f, 8f, 7f, 9.3431f, 7f, 11f)
                cubicTo(7f, 12.6569f, 8.3431f, 14f, 10f, 14f)
                close()
            }
        }

        /** Heroicons sparkles (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val sparkles: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(15.98f, 1.804f)
                cubicTo(15.8854f, 1.3379f, 15.4756f, 1.003f, 15f, 1.003f)
                cubicTo(14.5244f, 1.003f, 14.1146f, 1.3379f, 14.02f, 1.804f)
                lineTo(13.78f, 2.996f)
                cubicTo(13.7011f, 3.3919f, 13.3918f, 3.7016f, 12.996f, 3.781f)
                lineTo(11.804f, 4.019f)
                cubicTo(11.3356f, 4.1116f, 10.998f, 4.5225f, 10.998f, 5f)
                cubicTo(10.998f, 5.4775f, 11.3356f, 5.8884f, 11.804f, 5.981f)
                lineTo(12.996f, 6.219f)
                cubicTo(13.3922f, 6.2981f, 13.7019f, 6.6078f, 13.781f, 7.004f)
                lineTo(14.019f, 8.196f)
                cubicTo(14.1116f, 8.6644f, 14.5225f, 9.002f, 15f, 9.002f)
                cubicTo(15.4775f, 9.002f, 15.8884f, 8.6644f, 15.981f, 8.196f)
                lineTo(16.219f, 7.004f)
                cubicTo(16.2981f, 6.6078f, 16.6078f, 6.2981f, 17.004f, 6.219f)
                lineTo(18.196f, 5.981f)
                cubicTo(18.6644f, 5.8884f, 19.002f, 5.4775f, 19.002f, 5f)
                cubicTo(19.002f, 4.5225f, 18.6644f, 4.1116f, 18.196f, 4.019f)
                lineTo(17.004f, 3.781f)
                cubicTo(16.6078f, 3.7019f, 16.2981f, 3.3922f, 16.219f, 2.996f)
                lineTo(15.981f, 1.804f)
                close()
                moveTo(6.949f, 5.684f)
                cubicTo(6.8132f, 5.2752f, 6.4308f, 4.9993f, 6f, 4.9993f)
                cubicTo(5.5692f, 4.9993f, 5.1868f, 5.2752f, 5.051f, 5.684f)
                lineTo(4.368f, 7.735f)
                cubicTo(4.2685f, 8.0339f, 4.0339f, 8.2685f, 3.735f, 8.368f)
                lineTo(1.684f, 9.051f)
                cubicTo(1.2752f, 9.1868f, 0.9993f, 9.5692f, 0.9993f, 10f)
                cubicTo(0.9993f, 10.4308f, 1.2752f, 10.8132f, 1.684f, 10.949f)
                lineTo(3.735f, 11.633f)
                cubicTo(4.0337f, 11.7323f, 4.2682f, 11.9664f, 4.368f, 12.265f)
                lineTo(5.051f, 14.316f)
                cubicTo(5.1868f, 14.7248f, 5.5692f, 15.0007f, 6f, 15.0007f)
                cubicTo(6.4308f, 15.0007f, 6.8132f, 14.7248f, 6.949f, 14.316f)
                lineTo(7.632f, 12.265f)
                cubicTo(7.7315f, 11.9661f, 7.9661f, 11.7315f, 8.265f, 11.632f)
                lineTo(10.316f, 10.949f)
                cubicTo(10.7248f, 10.8132f, 11.0007f, 10.4308f, 11.0007f, 10f)
                cubicTo(11.0007f, 9.5692f, 10.7248f, 9.1868f, 10.316f, 9.051f)
                lineTo(8.265f, 8.368f)
                cubicTo(7.9661f, 8.2685f, 7.7315f, 8.0339f, 7.632f, 7.735f)
                lineTo(6.95f, 5.684f)
                close()
                moveTo(13.949f, 13.684f)
                cubicTo(13.8132f, 13.2752f, 13.4308f, 12.9993f, 13f, 12.9993f)
                cubicTo(12.5692f, 12.9993f, 12.1868f, 13.2752f, 12.051f, 13.684f)
                lineTo(11.867f, 14.235f)
                cubicTo(11.7677f, 14.5337f, 11.5336f, 14.7682f, 11.235f, 14.868f)
                lineTo(10.684f, 15.051f)
                cubicTo(10.2752f, 15.1868f, 9.9993f, 15.5692f, 9.9993f, 16f)
                cubicTo(9.9993f, 16.4308f, 10.2752f, 16.8132f, 10.684f, 16.949f)
                lineTo(11.235f, 17.132f)
                cubicTo(11.5339f, 17.2315f, 11.7685f, 17.4661f, 11.868f, 17.765f)
                lineTo(12.051f, 18.316f)
                cubicTo(12.1868f, 18.7248f, 12.5692f, 19.0007f, 13f, 19.0007f)
                cubicTo(13.4308f, 19.0007f, 13.8132f, 18.7248f, 13.949f, 18.316f)
                lineTo(14.133f, 17.765f)
                cubicTo(14.2323f, 17.4663f, 14.4664f, 17.2318f, 14.765f, 17.132f)
                lineTo(15.316f, 16.949f)
                cubicTo(15.7248f, 16.8132f, 16.0007f, 16.4308f, 16.0007f, 16f)
                cubicTo(16.0007f, 15.5692f, 15.7248f, 15.1868f, 15.316f, 15.051f)
                lineTo(14.765f, 14.867f)
                cubicTo(14.4663f, 14.7677f, 14.2318f, 14.5336f, 14.132f, 14.235f)
                lineTo(13.949f, 13.684f)
                close()
            }
        }

        /** Heroicons cube (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val cube: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(10.362f, 1.093f)
                cubicTo(10.1366f, 0.9688f, 9.8634f, 0.9688f, 9.638f, 1.093f)
                lineTo(2.523f, 5.018f)
                lineTo(10f, 9.143f)
                lineTo(17.477f, 5.018f)
                lineTo(10.362f, 1.093f)
                close()
                moveTo(18f, 6.443f)
                lineTo(10.75f, 10.443f)
                lineTo(10.75f, 18.693f)
                lineTo(17.612f, 14.907f)
                cubicTo(17.8514f, 14.7751f, 18.0001f, 14.5233f, 18f, 14.25f)
                lineTo(18f, 6.443f)
                close()
                moveTo(9.25f, 18.693f)
                lineTo(9.25f, 10.443f)
                lineTo(2f, 6.443f)
                lineTo(2f, 14.25f)
                cubicTo(1.9999f, 14.5233f, 2.1486f, 14.7751f, 2.388f, 14.907f)
                lineTo(9.25f, 18.693f)
                close()
            }
        }

        /** Heroicons cog-6-tooth (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val cog6Tooth: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(7.84f, 1.804f)
                cubicTo(7.9334f, 1.3367f, 8.3435f, 1.0003f, 8.82f, 1f)
                lineTo(11.18f, 1f)
                cubicTo(11.6565f, 1.0003f, 12.0666f, 1.3367f, 12.16f, 1.804f)
                lineTo(12.491f, 3.456f)
                cubicTo(13.1895f, 3.7222f, 13.8407f, 4.0986f, 14.42f, 4.571f)
                lineTo(16.018f, 4.031f)
                cubicTo(16.4693f, 3.8785f, 16.9656f, 4.0655f, 17.204f, 4.478f)
                lineTo(18.384f, 6.522f)
                cubicTo(18.6225f, 6.9346f, 18.5367f, 7.4581f, 18.179f, 7.773f)
                lineTo(16.912f, 8.886f)
                cubicTo(17.0301f, 9.624f, 17.0301f, 10.376f, 16.912f, 11.114f)
                lineTo(18.179f, 12.227f)
                cubicTo(18.5365f, 12.5415f, 18.6227f, 13.0644f, 18.385f, 13.477f)
                lineTo(17.205f, 15.522f)
                cubicTo(16.9665f, 15.935f, 16.4696f, 16.1221f, 16.018f, 15.969f)
                lineTo(14.42f, 15.429f)
                cubicTo(13.8407f, 15.9014f, 13.1895f, 16.2778f, 12.491f, 16.544f)
                lineTo(12.161f, 18.196f)
                cubicTo(12.0676f, 18.6633f, 11.6575f, 18.9997f, 11.181f, 19f)
                lineTo(8.82f, 19f)
                cubicTo(8.3435f, 18.9997f, 7.9334f, 18.6633f, 7.84f, 18.196f)
                lineTo(7.509f, 16.544f)
                cubicTo(6.8105f, 16.2778f, 6.1593f, 15.9014f, 5.58f, 15.429f)
                lineTo(3.982f, 15.969f)
                cubicTo(3.5307f, 16.1215f, 3.0344f, 15.9345f, 2.796f, 15.522f)
                lineTo(1.616f, 13.478f)
                cubicTo(1.3775f, 13.0654f, 1.4633f, 12.5419f, 1.821f, 12.227f)
                lineTo(3.088f, 11.113f)
                cubicTo(2.97f, 10.3754f, 2.97f, 9.6236f, 3.088f, 8.886f)
                lineTo(1.821f, 7.773f)
                cubicTo(1.4635f, 7.4585f, 1.3773f, 6.9356f, 1.615f, 6.523f)
                lineTo(2.795f, 4.478f)
                cubicTo(3.0335f, 4.065f, 3.5304f, 3.8779f, 3.982f, 4.031f)
                lineTo(5.58f, 4.571f)
                cubicTo(6.1596f, 4.0985f, 6.8112f, 3.7221f, 7.51f, 3.456f)
                lineTo(7.84f, 1.804f)
                close()
                moveTo(10f, 13f)
                cubicTo(11.6569f, 13f, 13f, 11.6569f, 13f, 10f)
                cubicTo(13f, 8.3431f, 11.6569f, 7f, 10f, 7f)
                cubicTo(8.3431f, 7f, 7f, 8.3431f, 7f, 10f)
                cubicTo(7f, 11.6569f, 8.3431f, 13f, 10f, 13f)
                close()
            }
        }

        /** Heroicons arrow-up-tray (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val arrowUpTray: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(9.25f, 13.25f)
                cubicTo(9.25f, 13.6642f, 9.5858f, 14f, 10f, 14f)
                cubicTo(10.4142f, 14f, 10.75f, 13.6642f, 10.75f, 13.25f)
                lineTo(10.75f, 4.636f)
                lineTo(13.705f, 7.765f)
                cubicTo(13.9914f, 8.0556f, 14.4577f, 8.0639f, 14.7543f, 7.7836f)
                cubicTo(15.0508f, 7.5034f, 15.0689f, 7.0374f, 14.795f, 6.735f)
                lineTo(10.545f, 2.235f)
                cubicTo(10.4033f, 2.0852f, 10.2062f, 2.0002f, 10f, 2.0002f)
                cubicTo(9.7938f, 2.0002f, 9.5967f, 2.0852f, 9.455f, 2.235f)
                lineTo(5.205f, 6.735f)
                cubicTo(5.0143f, 6.9285f, 4.9431f, 7.2101f, 5.019f, 7.471f)
                cubicTo(5.0949f, 7.7319f, 5.306f, 7.9313f, 5.5707f, 7.9923f)
                cubicTo(5.8355f, 8.0534f, 6.1126f, 7.9664f, 6.295f, 7.765f)
                lineTo(9.25f, 4.636f)
                lineTo(9.25f, 13.25f)
                close()
            }
            path {
                moveTo(3.5f, 12.75f)
                cubicTo(3.5f, 12.3358f, 3.1642f, 12f, 2.75f, 12f)
                cubicTo(2.3358f, 12f, 2f, 12.3358f, 2f, 12.75f)
                lineTo(2f, 15.25f)
                cubicTo(2f, 16.7688f, 3.2312f, 18f, 4.75f, 18f)
                lineTo(15.25f, 18f)
                cubicTo(16.7688f, 18f, 18f, 16.7688f, 18f, 15.25f)
                lineTo(18f, 12.75f)
                cubicTo(18f, 12.3358f, 17.6642f, 12f, 17.25f, 12f)
                cubicTo(16.8358f, 12f, 16.5f, 12.3358f, 16.5f, 12.75f)
                lineTo(16.5f, 15.25f)
                cubicTo(16.5f, 15.94f, 15.94f, 16.5f, 15.25f, 16.5f)
                lineTo(4.75f, 16.5f)
                cubicTo(4.06f, 16.5f, 3.5f, 15.94f, 3.5f, 15.25f)
                lineTo(3.5f, 12.75f)
                close()
            }
        }

        /** Heroicons arrow-down-tray (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val arrowDownTray: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(10.75f, 2.75f)
                cubicTo(10.75f, 2.3358f, 10.4142f, 2f, 10f, 2f)
                cubicTo(9.5858f, 2f, 9.25f, 2.3358f, 9.25f, 2.75f)
                lineTo(9.25f, 11.364f)
                lineTo(6.295f, 8.235f)
                cubicTo(6.1126f, 8.0336f, 5.8355f, 7.9466f, 5.5707f, 8.0077f)
                cubicTo(5.306f, 8.0687f, 5.0949f, 8.2681f, 5.019f, 8.529f)
                cubicTo(4.9431f, 8.7899f, 5.0143f, 9.0715f, 5.205f, 9.265f)
                lineTo(9.455f, 13.765f)
                cubicTo(9.5967f, 13.9148f, 9.7938f, 13.9998f, 10f, 13.9998f)
                cubicTo(10.2062f, 13.9998f, 10.4033f, 13.9148f, 10.545f, 13.765f)
                lineTo(14.795f, 9.265f)
                cubicTo(15.0689f, 8.9626f, 15.0508f, 8.4966f, 14.7543f, 8.2164f)
                cubicTo(14.4577f, 7.9361f, 13.9914f, 7.9444f, 13.705f, 8.235f)
                lineTo(10.75f, 11.364f)
                lineTo(10.75f, 2.75f)
                close()
            }
            path {
                moveTo(3.5f, 12.75f)
                cubicTo(3.5f, 12.3358f, 3.1642f, 12f, 2.75f, 12f)
                cubicTo(2.3358f, 12f, 2f, 12.3358f, 2f, 12.75f)
                lineTo(2f, 15.25f)
                cubicTo(2f, 16.7688f, 3.2312f, 18f, 4.75f, 18f)
                lineTo(15.25f, 18f)
                cubicTo(16.7688f, 18f, 18f, 16.7688f, 18f, 15.25f)
                lineTo(18f, 12.75f)
                cubicTo(18f, 12.3358f, 17.6642f, 12f, 17.25f, 12f)
                cubicTo(16.8358f, 12f, 16.5f, 12.3358f, 16.5f, 12.75f)
                lineTo(16.5f, 15.25f)
                cubicTo(16.5f, 15.94f, 15.94f, 16.5f, 15.25f, 16.5f)
                lineTo(4.75f, 16.5f)
                cubicTo(4.06f, 16.5f, 3.5f, 15.94f, 3.5f, 15.25f)
                lineTo(3.5f, 12.75f)
                close()
            }
        }

        /** Heroicons puzzle-piece (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val puzzlePiece: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(12f, 4.467f)
                cubicTo(12f, 4.062f, 12.262f, 3.717f, 12.559f, 3.44f)
                cubicTo(12.835f, 3.183f, 13f, 2.856f, 13f, 2.5f)
                cubicTo(13f, 1.672f, 12.105f, 1f, 11f, 1f)
                cubicTo(9.895f, 1f, 9f, 1.672f, 9f, 2.5f)
                cubicTo(9f, 2.862f, 9.171f, 3.194f, 9.456f, 3.453f)
                cubicTo(9.746f, 3.718f, 10f, 4.053f, 10f, 4.447f)
                cubicTo(10.0021f, 4.7148f, 9.8932f, 4.9715f, 9.6992f, 5.156f)
                cubicTo(9.5051f, 5.3406f, 9.2433f, 5.4365f, 8.976f, 5.421f)
                cubicTo(7.9678f, 5.3574f, 6.9624f, 5.2554f, 5.962f, 5.115f)
                cubicTo(5.7289f, 5.0823f, 5.4939f, 5.1609f, 5.3274f, 5.3274f)
                cubicTo(5.1609f, 5.4939f, 5.0823f, 5.7289f, 5.115f, 5.962f)
                cubicTo(5.255f, 6.955f, 5.357f, 7.961f, 5.421f, 8.976f)
                cubicTo(5.4365f, 9.2433f, 5.3406f, 9.5051f, 5.156f, 9.6992f)
                cubicTo(4.9715f, 9.8932f, 4.7148f, 10.0021f, 4.447f, 10f)
                cubicTo(4.054f, 10f, 3.718f, 9.747f, 3.453f, 9.456f)
                cubicTo(3.194f, 9.17f, 2.862f, 9f, 2.5f, 9f)
                cubicTo(1.672f, 9f, 1f, 9.895f, 1f, 11f)
                cubicTo(1f, 12.105f, 1.672f, 13f, 2.5f, 13f)
                cubicTo(2.856f, 13f, 3.183f, 12.835f, 3.44f, 12.559f)
                cubicTo(3.716f, 12.262f, 4.062f, 12f, 4.467f, 12f)
                cubicTo(4.7385f, 11.9979f, 4.999f, 12.1067f, 5.1885f, 12.3011f)
                cubicTo(5.378f, 12.4954f, 5.48f, 12.7587f, 5.471f, 13.03f)
                cubicTo(5.4234f, 14.279f, 5.317f, 15.525f, 5.152f, 16.764f)
                cubicTo(5.0975f, 17.1729f, 5.3834f, 17.5491f, 5.792f, 17.606f)
                cubicTo(6.842f, 17.752f, 7.903f, 17.858f, 8.976f, 17.924f)
                cubicTo(9.2435f, 17.9389f, 9.5053f, 17.8425f, 9.6993f, 17.6577f)
                cubicTo(9.8932f, 17.4728f, 10.0021f, 17.2159f, 10f, 16.948f)
                cubicTo(10f, 16.554f, 9.746f, 16.218f, 9.455f, 15.953f)
                cubicTo(9.171f, 15.693f, 9f, 15.362f, 9f, 15f)
                cubicTo(9f, 14.172f, 9.895f, 13.5f, 11f, 13.5f)
                cubicTo(12.105f, 13.5f, 13f, 14.172f, 13f, 15f)
                cubicTo(13f, 15.356f, 12.835f, 15.683f, 12.559f, 15.94f)
                cubicTo(12.262f, 16.216f, 12f, 16.562f, 12f, 16.967f)
                cubicTo(11.998f, 17.2385f, 12.1066f, 17.4992f, 12.301f, 17.6888f)
                cubicTo(12.4954f, 17.8785f, 12.7586f, 17.9807f, 13.03f, 17.972f)
                cubicTo(14.367f, 17.922f, 15.689f, 17.81f, 16.991f, 17.635f)
                cubicTo(17.3264f, 17.5902f, 17.5902f, 17.3264f, 17.635f, 16.991f)
                cubicTo(17.81f, 15.689f, 17.923f, 14.367f, 17.972f, 13.03f)
                cubicTo(17.9807f, 12.7586f, 17.8785f, 12.4954f, 17.6888f, 12.301f)
                cubicTo(17.4992f, 12.1066f, 17.2385f, 11.998f, 16.967f, 12f)
                cubicTo(16.562f, 12f, 16.217f, 12.262f, 15.94f, 12.559f)
                cubicTo(15.683f, 12.835f, 15.356f, 13f, 15f, 13f)
                cubicTo(14.172f, 13f, 13.5f, 12.105f, 13.5f, 11f)
                cubicTo(13.5f, 9.895f, 14.172f, 9f, 15f, 9f)
                cubicTo(15.362f, 9f, 15.694f, 9.17f, 15.953f, 9.455f)
                cubicTo(16.218f, 9.746f, 16.554f, 10f, 16.948f, 10f)
                cubicTo(17.2159f, 10.0021f, 17.4728f, 9.8932f, 17.6577f, 9.6993f)
                cubicTo(17.8425f, 9.5053f, 17.9389f, 9.2435f, 17.924f, 8.976f)
                cubicTo(17.8593f, 7.9109f, 17.7532f, 6.8488f, 17.606f, 5.792f)
                cubicTo(17.5491f, 5.3834f, 17.1729f, 5.0975f, 16.764f, 5.152f)
                cubicTo(15.536f, 5.316f, 14.291f, 5.423f, 13.03f, 5.471f)
                cubicTo(12.7587f, 5.48f, 12.4954f, 5.378f, 12.3011f, 5.1885f)
                cubicTo(12.1067f, 4.999f, 11.9979f, 4.7385f, 12f, 4.467f)
                close()
            }
        }

        /** Heroicons pencil-square (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val pencilSquare: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(5.433f, 13.917f)
                lineTo(6.695f, 10.762f)
                cubicTo(6.8961f, 10.2594f, 7.1972f, 9.8028f, 7.58f, 9.42f)
                lineTo(14.5f, 2.502f)
                cubicTo(15.3284f, 1.6736f, 16.6716f, 1.6736f, 17.5f, 2.502f)
                cubicTo(18.3284f, 3.3304f, 18.3284f, 4.6736f, 17.5f, 5.502f)
                lineTo(10.58f, 12.42f)
                cubicTo(10.197f, 12.803f, 9.74f, 13.105f, 9.237f, 13.306f)
                lineTo(6.083f, 14.568f)
                cubicTo(5.8973f, 14.6423f, 5.6851f, 14.5988f, 5.5436f, 14.4574f)
                cubicTo(5.4022f, 14.3159f, 5.3587f, 14.1037f, 5.433f, 13.918f)
                close()
            }
            path {
                moveTo(3.5f, 5.75f)
                cubicTo(3.5f, 5.06f, 4.06f, 4.5f, 4.75f, 4.5f)
                lineTo(10f, 4.5f)
                cubicTo(10.4142f, 4.5f, 10.75f, 4.1642f, 10.75f, 3.75f)
                cubicTo(10.75f, 3.3358f, 10.4142f, 3f, 10f, 3f)
                lineTo(4.75f, 3f)
                cubicTo(3.2312f, 3f, 2f, 4.2312f, 2f, 5.75f)
                lineTo(2f, 15.25f)
                cubicTo(2f, 16.7688f, 3.2312f, 18f, 4.75f, 18f)
                lineTo(14.25f, 18f)
                cubicTo(15.7688f, 18f, 17f, 16.7688f, 17f, 15.25f)
                lineTo(17f, 10f)
                cubicTo(17f, 9.5858f, 16.6642f, 9.25f, 16.25f, 9.25f)
                cubicTo(15.8358f, 9.25f, 15.5f, 9.5858f, 15.5f, 10f)
                lineTo(15.5f, 15.25f)
                cubicTo(15.5f, 15.94f, 14.94f, 16.5f, 14.25f, 16.5f)
                lineTo(4.75f, 16.5f)
                cubicTo(4.06f, 16.5f, 3.5f, 15.94f, 3.5f, 15.25f)
                lineTo(3.5f, 5.75f)
                close()
            }
        }

        /** Heroicons play (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val play: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(6.3f, 2.84f)
                cubicTo(5.8377f, 2.5485f, 5.2534f, 2.5315f, 4.7749f, 2.7957f)
                cubicTo(4.2965f, 3.0599f, 3.9996f, 3.5635f, 4f, 4.11f)
                lineTo(4f, 15.89f)
                cubicTo(3.9996f, 16.4365f, 4.2965f, 16.9401f, 4.7749f, 17.2043f)
                cubicTo(5.2534f, 17.4685f, 5.8377f, 17.4515f, 6.3f, 17.16f)
                lineTo(15.644f, 11.269f)
                cubicTo(16.0798f, 10.9943f, 16.3442f, 10.5152f, 16.3442f, 10f)
                cubicTo(16.3442f, 9.4848f, 16.0798f, 9.0057f, 15.644f, 8.731f)
                lineTo(6.3f, 2.841f)
                close()
            }
        }

        /** Heroicons magnifying-glass (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val magnifyingGlass: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(9f, 3.5f)
                cubicTo(5.9624f, 3.5f, 3.5f, 5.9624f, 3.5f, 9f)
                cubicTo(3.5f, 12.0376f, 5.9624f, 14.5f, 9f, 14.5f)
                cubicTo(12.0376f, 14.5f, 14.5f, 12.0376f, 14.5f, 9f)
                cubicTo(14.5f, 5.9624f, 12.0376f, 3.5f, 9f, 3.5f)
                close()
                moveTo(2f, 9f)
                cubicTo(2.0003f, 5.9247f, 4.0076f, 3.2098f, 6.9477f, 2.3082f)
                cubicTo(9.8878f, 1.4066f, 13.072f, 2.5295f, 14.7963f, 5.0759f)
                cubicTo(16.5205f, 7.6223f, 16.3808f, 10.9958f, 14.452f, 13.391f)
                lineTo(17.78f, 16.72f)
                cubicTo(17.9807f, 16.907f, 18.0632f, 17.1886f, 17.9954f, 17.4543f)
                cubicTo(17.9275f, 17.72f, 17.72f, 17.9275f, 17.4543f, 17.9954f)
                cubicTo(17.1886f, 18.0632f, 16.907f, 17.9807f, 16.72f, 17.78f)
                lineTo(13.391f, 14.452f)
                cubicTo(11.2921f, 16.1426f, 8.409f, 16.4781f, 5.9779f, 15.3145f)
                cubicTo(3.5469f, 14.151f, 1.9998f, 11.6951f, 2f, 9f)
                close()
            }
        }

        /** Heroicons video-camera (20/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val videoCamera: UiImageVector = uiImageVector(
            defaultWidth = 20f.dp,
            defaultHeight = 20f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(3.25f, 4f)
                cubicTo(2.0074f, 4f, 1f, 5.0074f, 1f, 6.25f)
                lineTo(1f, 13.75f)
                cubicTo(1f, 14.9926f, 2.0074f, 16f, 3.25f, 16f)
                lineTo(10.75f, 16f)
                cubicTo(11.9926f, 16f, 13f, 14.9926f, 13f, 13.75f)
                lineTo(13f, 6.25f)
                cubicTo(13f, 5.0074f, 11.9926f, 4f, 10.75f, 4f)
                lineTo(3.25f, 4f)
                close()
                moveTo(19f, 4.75f)
                cubicTo(18.9997f, 4.4469f, 18.817f, 4.1737f, 18.5369f, 4.0577f)
                cubicTo(18.2568f, 3.9417f, 17.9345f, 4.0058f, 17.72f, 4.22f)
                lineTo(14.72f, 7.22f)
                cubicTo(14.5793f, 7.3605f, 14.5002f, 7.5512f, 14.5f, 7.75f)
                lineTo(14.5f, 12.25f)
                cubicTo(14.5f, 12.449f, 14.579f, 12.64f, 14.72f, 12.78f)
                lineTo(17.72f, 15.78f)
                cubicTo(17.9345f, 15.9942f, 18.2568f, 16.0583f, 18.5369f, 15.9423f)
                cubicTo(18.817f, 15.8263f, 18.9997f, 15.5531f, 19f, 15.25f)
                lineTo(19f, 4.75f)
                close()
            }
        }
    }

    /** Heroicons' `solid/24/solid` tier -- the full-size solid glyphs. Genuinely different
     * path data from [Solid20Mini], not a rescale. */
    object Solid24 {
        /** Heroicons `arrow-down-on-square-stack` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val arrowDownOnSquareStack: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(9.75f, 6.75f)
                lineTo(6.75f, 6.75f)
                cubicTo(5.0931f, 6.75f, 3.75f, 8.0931f, 3.75f, 9.75f)
                lineTo(3.75f, 17.25f)
                cubicTo(3.75f, 18.9069f, 5.0931f, 20.25f, 6.75f, 20.25f)
                lineTo(14.25f, 20.25f)
                cubicTo(15.9069f, 20.25f, 17.25f, 18.9069f, 17.25f, 17.25f)
                lineTo(17.25f, 9.75f)
                cubicTo(17.25f, 8.0931f, 15.9069f, 6.75f, 14.25f, 6.75f)
                lineTo(11.25f, 6.75f)
                lineTo(11.25f, 1.5f)
                cubicTo(11.25f, 1.0858f, 10.9142f, 0.75f, 10.5f, 0.75f)
                cubicTo(10.0858f, 0.75f, 9.75f, 1.0858f, 9.75f, 1.5f)
                lineTo(9.75f, 6.75f)
                close()
                moveTo(9.75f, 6.75f)
                lineTo(11.25f, 6.75f)
                lineTo(11.25f, 12.44f)
                lineTo(12.97f, 10.72f)
                cubicTo(13.157f, 10.5193f, 13.4386f, 10.4368f, 13.7043f, 10.5046f)
                cubicTo(13.97f, 10.5725f, 14.1775f, 10.78f, 14.2454f, 11.0457f)
                cubicTo(14.3132f, 11.3114f, 14.2307f, 11.593f, 14.03f, 11.78f)
                lineTo(11.03f, 14.78f)
                cubicTo(10.7372f, 15.0725f, 10.2628f, 15.0725f, 9.97f, 14.78f)
                lineTo(6.97f, 11.78f)
                cubicTo(6.7693f, 11.593f, 6.6868f, 11.3114f, 6.7546f, 11.0457f)
                cubicTo(6.8225f, 10.78f, 7.03f, 10.5725f, 7.2957f, 10.5046f)
                cubicTo(7.5614f, 10.4368f, 7.843f, 10.5193f, 8.03f, 10.72f)
                lineTo(9.75f, 12.44f)
                lineTo(9.75f, 6.75f)
                close()
            }
            path {
                moveTo(7.151f, 21.75f)
                cubicTo(7.6869f, 22.6786f, 8.6778f, 23.2505f, 9.75f, 23.25f)
                lineTo(17.25f, 23.25f)
                cubicTo(18.9069f, 23.25f, 20.25f, 21.9069f, 20.25f, 20.25f)
                lineTo(20.25f, 12.75f)
                cubicTo(20.25f, 11.64f, 19.647f, 10.67f, 18.75f, 10.151f)
                lineTo(18.75f, 17.25f)
                cubicTo(18.75f, 19.7353f, 16.7353f, 21.75f, 14.25f, 21.75f)
                lineTo(7.151f, 21.75f)
                close()
            }
        }

        /** Heroicons `arrow-up-on-square-stack` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val arrowUpOnSquareStack: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path {
                moveTo(9.97f, 0.97f)
                cubicTo(10.2628f, 0.6775f, 10.7372f, 0.6775f, 11.03f, 0.97f)
                lineTo(14.03f, 3.97f)
                cubicTo(14.3054f, 4.2655f, 14.2972f, 4.726f, 14.0116f, 5.0116f)
                cubicTo(13.726f, 5.2972f, 13.2655f, 5.3054f, 12.97f, 5.03f)
                lineTo(11.25f, 3.31f)
                lineTo(11.25f, 6.75f)
                lineTo(9.75f, 6.75f)
                lineTo(9.75f, 3.31f)
                lineTo(8.03f, 5.03f)
                cubicTo(7.7345f, 5.3054f, 7.274f, 5.2972f, 6.9884f, 5.0116f)
                cubicTo(6.7028f, 4.726f, 6.6946f, 4.2655f, 6.97f, 3.97f)
                lineTo(9.97f, 0.97f)
                close()
                moveTo(9.75f, 6.75f)
                lineTo(9.75f, 12.75f)
                cubicTo(9.75f, 13.1642f, 10.0858f, 13.5f, 10.5f, 13.5f)
                cubicTo(10.9142f, 13.5f, 11.25f, 13.1642f, 11.25f, 12.75f)
                lineTo(11.25f, 6.75f)
                lineTo(14.25f, 6.75f)
                cubicTo(15.9069f, 6.75f, 17.25f, 8.0931f, 17.25f, 9.75f)
                lineTo(17.25f, 17.25f)
                cubicTo(17.25f, 18.9069f, 15.9069f, 20.25f, 14.25f, 20.25f)
                lineTo(6.75f, 20.25f)
                cubicTo(5.0931f, 20.25f, 3.75f, 18.9069f, 3.75f, 17.25f)
                lineTo(3.75f, 9.75f)
                cubicTo(3.75f, 8.0931f, 5.0931f, 6.75f, 6.75f, 6.75f)
                lineTo(9.75f, 6.75f)
                close()
            }
            path {
                moveTo(7.151f, 21.75f)
                cubicTo(7.6869f, 22.6786f, 8.6778f, 23.2505f, 9.75f, 23.25f)
                lineTo(17.25f, 23.25f)
                cubicTo(18.9069f, 23.25f, 20.25f, 21.9069f, 20.25f, 20.25f)
                lineTo(20.25f, 12.75f)
                cubicTo(20.25f, 11.64f, 19.647f, 10.67f, 18.75f, 10.151f)
                lineTo(18.75f, 17.25f)
                cubicTo(18.75f, 19.7353f, 16.7353f, 21.75f, 14.25f, 21.75f)
                lineTo(7.151f, 21.75f)
                close()
            }
        }

        /** Heroicons `circle-stack` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val circleStack: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path {
                moveTo(21f, 6.375f)
                cubicTo(21f, 9.067f, 16.97f, 11.25f, 12f, 11.25f)
                cubicTo(7.03f, 11.25f, 3f, 9.067f, 3f, 6.375f)
                cubicTo(3f, 3.683f, 7.03f, 1.5f, 12f, 1.5f)
                cubicTo(16.97f, 1.5f, 21f, 3.683f, 21f, 6.375f)
                close()
            }
            path {
                moveTo(12f, 12.75f)
                cubicTo(14.685f, 12.75f, 17.19f, 12.164f, 19.078f, 11.141f)
                cubicTo(19.7728f, 10.7721f, 20.4116f, 10.3061f, 20.975f, 9.757f)
                cubicTo(20.991f, 9.878f, 21f, 10.001f, 21f, 10.125f)
                cubicTo(21f, 12.817f, 16.97f, 15f, 12f, 15f)
                cubicTo(7.03f, 15f, 3f, 12.817f, 3f, 10.125f)
                cubicTo(3f, 10.001f, 3.009f, 9.878f, 3.025f, 9.757f)
                cubicTo(3.5884f, 10.3061f, 4.2272f, 10.7721f, 4.922f, 11.141f)
                cubicTo(6.809f, 12.164f, 9.315f, 12.75f, 12f, 12.75f)
                close()
            }
            path {
                moveTo(12f, 16.5f)
                cubicTo(14.685f, 16.5f, 17.19f, 15.914f, 19.078f, 14.891f)
                cubicTo(19.7729f, 14.5221f, 20.4116f, 14.0561f, 20.975f, 13.507f)
                cubicTo(20.991f, 13.628f, 21f, 13.751f, 21f, 13.875f)
                cubicTo(21f, 16.567f, 16.97f, 18.75f, 12f, 18.75f)
                cubicTo(7.03f, 18.75f, 3f, 16.567f, 3f, 13.875f)
                cubicTo(3f, 13.751f, 3.009f, 13.628f, 3.025f, 13.507f)
                cubicTo(3.5884f, 14.0561f, 4.2272f, 14.5221f, 4.922f, 14.891f)
                cubicTo(6.809f, 15.914f, 9.315f, 16.5f, 12f, 16.5f)
                close()
            }
            path {
                moveTo(12f, 20.25f)
                cubicTo(14.685f, 20.25f, 17.19f, 19.664f, 19.078f, 18.641f)
                cubicTo(19.7729f, 18.2721f, 20.4116f, 17.8061f, 20.975f, 17.257f)
                cubicTo(20.991f, 17.378f, 21f, 17.501f, 21f, 17.625f)
                cubicTo(21f, 20.317f, 16.97f, 22.5f, 12f, 22.5f)
                cubicTo(7.03f, 22.5f, 3f, 20.317f, 3f, 17.625f)
                cubicTo(3f, 17.501f, 3.009f, 17.378f, 3.025f, 17.257f)
                cubicTo(3.5884f, 17.8061f, 4.2272f, 18.2721f, 4.922f, 18.641f)
                cubicTo(6.809f, 19.664f, 9.315f, 20.25f, 12f, 20.25f)
                close()
            }
        }

        /** Heroicons `inbox-stack` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val inboxStack: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(1.5f, 9.832f)
                lineTo(1.5f, 11.625f)
                cubicTo(1.5f, 12.661f, 2.34f, 13.5f, 3.375f, 13.5f)
                lineTo(20.625f, 13.5f)
                cubicTo(21.66f, 13.5f, 22.5f, 12.66f, 22.5f, 11.625f)
                lineTo(22.5f, 9.832f)
                cubicTo(22.5f, 9.116f, 22.2439f, 8.4237f, 21.778f, 7.88f)
                lineTo(18.493f, 4.048f)
                cubicTo(17.9231f, 3.3829f, 17.0909f, 3f, 16.215f, 3f)
                lineTo(7.785f, 3f)
                cubicTo(6.9091f, 3f, 6.0769f, 3.3829f, 5.507f, 4.048f)
                lineTo(2.222f, 7.88f)
                cubicTo(1.7561f, 8.4237f, 1.5f, 9.116f, 1.5f, 9.832f)
                close()
                moveTo(7.785f, 4.5f)
                cubicTo(7.347f, 4.5f, 6.931f, 4.6914f, 6.646f, 5.024f)
                lineTo(3.881f, 8.25f)
                lineTo(7.046f, 8.25f)
                cubicTo(8.049f, 8.2501f, 8.9857f, 8.7514f, 9.542f, 9.586f)
                lineTo(9.706f, 9.832f)
                cubicTo(9.9842f, 10.2493f, 10.4525f, 10.5f, 10.954f, 10.5f)
                lineTo(13.046f, 10.5f)
                cubicTo(13.5475f, 10.5f, 14.0158f, 10.2493f, 14.294f, 9.832f)
                lineTo(14.458f, 9.586f)
                cubicTo(15.0143f, 8.7514f, 15.951f, 8.2501f, 16.954f, 8.25f)
                lineTo(20.119f, 8.25f)
                lineTo(17.354f, 5.024f)
                cubicTo(17.069f, 4.6914f, 16.653f, 4.5f, 16.215f, 4.5f)
                lineTo(7.785f, 4.5f)
                close()
            }
            path {
                moveTo(2.813f, 15f)
                cubicTo(2.088f, 15f, 1.5f, 15.588f, 1.5f, 16.313f)
                lineTo(1.5f, 18f)
                cubicTo(1.5f, 19.6569f, 2.8431f, 21f, 4.5f, 21f)
                lineTo(19.5f, 21f)
                cubicTo(21.1569f, 21f, 22.5f, 19.6569f, 22.5f, 18f)
                lineTo(22.5f, 16.312f)
                cubicTo(22.5f, 15.588f, 21.912f, 15f, 21.187f, 15f)
                lineTo(16.954f, 15f)
                cubicTo(15.951f, 15.0001f, 15.0143f, 15.5014f, 14.458f, 16.336f)
                lineTo(14.294f, 16.582f)
                cubicTo(14.0158f, 16.9993f, 13.5475f, 17.25f, 13.046f, 17.25f)
                lineTo(10.954f, 17.25f)
                cubicTo(10.4525f, 17.25f, 9.9842f, 16.9993f, 9.706f, 16.582f)
                lineTo(9.542f, 16.336f)
                cubicTo(8.9857f, 15.5014f, 8.049f, 15.0001f, 7.046f, 15f)
                lineTo(2.812f, 15f)
                close()
            }
        }

        /** Heroicons `rectangle-stack` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val rectangleStack: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path {
                moveTo(5.566f, 4.657f)
                cubicTo(5.9519f, 4.5523f, 6.3501f, 4.4996f, 6.75f, 4.5f)
                lineTo(17.25f, 4.5f)
                cubicTo(17.66f, 4.5f, 18.056f, 4.555f, 18.433f, 4.657f)
                cubicTo(17.9245f, 3.6413f, 16.8859f, 2.9998f, 15.75f, 3f)
                lineTo(8.25f, 3f)
                cubicTo(7.1137f, 2.9995f, 6.0747f, 3.6409f, 5.566f, 4.657f)
                close()
                moveTo(2.25f, 12f)
                cubicTo(2.25f, 10.3431f, 3.5931f, 9f, 5.25f, 9f)
                lineTo(18.75f, 9f)
                cubicTo(20.4069f, 9f, 21.75f, 10.3431f, 21.75f, 12f)
                lineTo(21.75f, 18f)
                cubicTo(21.75f, 19.6569f, 20.4069f, 21f, 18.75f, 21f)
                lineTo(5.25f, 21f)
                cubicTo(3.5931f, 21f, 2.25f, 19.6569f, 2.25f, 18f)
                lineTo(2.25f, 12f)
                close()
                moveTo(5.25f, 7.5f)
                cubicTo(4.84f, 7.5f, 4.444f, 7.555f, 4.066f, 7.657f)
                cubicTo(4.5747f, 6.6409f, 5.6137f, 5.9995f, 6.75f, 6f)
                lineTo(17.25f, 6f)
                cubicTo(18.3859f, 5.9998f, 19.4245f, 6.6413f, 19.933f, 7.657f)
                cubicTo(19.5474f, 7.5524f, 19.1496f, 7.4996f, 18.75f, 7.5f)
                lineTo(5.25f, 7.5f)
                close()
            }
        }

        /** Heroicons `server-stack` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val serverStack: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path {
                moveTo(5.507f, 4.048f)
                cubicTo(6.0769f, 3.3829f, 6.9091f, 3f, 7.785f, 3f)
                lineTo(16.215f, 3f)
                cubicTo(17.0909f, 3f, 17.9231f, 3.3829f, 18.493f, 4.048f)
                lineTo(20.215f, 6.056f)
                cubicTo(19.9785f, 6.0185f, 19.7394f, 5.9998f, 19.5f, 6f)
                lineTo(4.5f, 6f)
                cubicTo(4.257f, 6f, 4.018f, 6.02f, 3.785f, 6.056f)
                lineTo(5.507f, 4.048f)
                close()
            }
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(1.5f, 10.5f)
                cubicTo(1.5f, 8.8431f, 2.8431f, 7.5f, 4.5f, 7.5f)
                lineTo(19.5f, 7.5f)
                cubicTo(21.1569f, 7.5f, 22.5f, 8.8431f, 22.5f, 10.5f)
                cubicTo(22.5f, 12.1569f, 21.1569f, 13.5f, 19.5f, 13.5f)
                lineTo(4.5f, 13.5f)
                cubicTo(2.8431f, 13.5f, 1.5f, 12.1569f, 1.5f, 10.5f)
                close()
                moveTo(16.5f, 10.5f)
                cubicTo(16.5f, 10.9142f, 16.1642f, 11.25f, 15.75f, 11.25f)
                cubicTo(15.3358f, 11.25f, 15f, 10.9142f, 15f, 10.5f)
                cubicTo(15f, 10.0858f, 15.3358f, 9.75f, 15.75f, 9.75f)
                cubicTo(16.1642f, 9.75f, 16.5f, 10.0858f, 16.5f, 10.5f)
                close()
                moveTo(18.75f, 11.25f)
                cubicTo(19.1642f, 11.25f, 19.5f, 10.9142f, 19.5f, 10.5f)
                cubicTo(19.5f, 10.0858f, 19.1642f, 9.75f, 18.75f, 9.75f)
                cubicTo(18.3358f, 9.75f, 18f, 10.0858f, 18f, 10.5f)
                cubicTo(18f, 10.9142f, 18.3358f, 11.25f, 18.75f, 11.25f)
                close()
                moveTo(4.5f, 15f)
                cubicTo(2.8431f, 15f, 1.5f, 16.3431f, 1.5f, 18f)
                cubicTo(1.5f, 19.6569f, 2.8431f, 21f, 4.5f, 21f)
                lineTo(19.5f, 21f)
                cubicTo(21.1569f, 21f, 22.5f, 19.6569f, 22.5f, 18f)
                cubicTo(22.5f, 16.3431f, 21.1569f, 15f, 19.5f, 15f)
                lineTo(4.5f, 15f)
                close()
                moveTo(15.75f, 18.75f)
                cubicTo(16.1642f, 18.75f, 16.5f, 18.4142f, 16.5f, 18f)
                cubicTo(16.5f, 17.5858f, 16.1642f, 17.25f, 15.75f, 17.25f)
                cubicTo(15.3358f, 17.25f, 15f, 17.5858f, 15f, 18f)
                cubicTo(15f, 18.4142f, 15.3358f, 18.75f, 15.75f, 18.75f)
                close()
                moveTo(19.5f, 18f)
                cubicTo(19.5f, 18.4142f, 19.1642f, 18.75f, 18.75f, 18.75f)
                cubicTo(18.3358f, 18.75f, 18f, 18.4142f, 18f, 18f)
                cubicTo(18f, 17.5858f, 18.3358f, 17.25f, 18.75f, 17.25f)
                cubicTo(19.1642f, 17.25f, 19.5f, 17.5858f, 19.5f, 18f)
                close()
            }
        }

        /** Heroicons `square-2-stack` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val square2Stack: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path {
                moveTo(16.5f, 6f)
                cubicTo(16.5f, 4.3431f, 15.1569f, 3f, 13.5f, 3f)
                lineTo(6f, 3f)
                cubicTo(4.3431f, 3f, 3f, 4.3431f, 3f, 6f)
                lineTo(3f, 13.5f)
                cubicTo(3f, 15.1569f, 4.3431f, 16.5f, 6f, 16.5f)
                lineTo(6f, 10.5f)
                cubicTo(6f, 8.0147f, 8.0147f, 6f, 10.5f, 6f)
                lineTo(16.5f, 6f)
                close()
            }
            path {
                moveTo(18f, 7.5f)
                cubicTo(19.6569f, 7.5f, 21f, 8.8431f, 21f, 10.5f)
                lineTo(21f, 18f)
                cubicTo(21f, 19.6569f, 19.6569f, 21f, 18f, 21f)
                lineTo(10.5f, 21f)
                cubicTo(8.8431f, 21f, 7.5f, 19.6569f, 7.5f, 18f)
                lineTo(7.5f, 10.5f)
                cubicTo(7.5f, 8.8431f, 8.8431f, 7.5f, 10.5f, 7.5f)
                lineTo(18f, 7.5f)
                close()
            }
        }

        /** Heroicons `square-3-stack-3d` (24/solid), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val square3Stack3d: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path {
                moveTo(11.644f, 1.59f)
                cubicTo(11.8662f, 1.4702f, 12.1338f, 1.4702f, 12.356f, 1.59f)
                lineTo(22.106f, 6.84f)
                cubicTo(22.3486f, 6.9709f, 22.4998f, 7.2244f, 22.4998f, 7.5f)
                cubicTo(22.4998f, 7.7756f, 22.3486f, 8.0291f, 22.106f, 8.16f)
                lineTo(12.356f, 13.41f)
                cubicTo(12.1338f, 13.5298f, 11.8662f, 13.5298f, 11.644f, 13.41f)
                lineTo(1.894f, 8.16f)
                cubicTo(1.6514f, 8.0291f, 1.5002f, 7.7756f, 1.5002f, 7.5f)
                cubicTo(1.5002f, 7.2244f, 1.6514f, 6.9709f, 1.894f, 6.84f)
                lineTo(11.644f, 1.59f)
                close()
            }
            path {
                moveTo(3.265f, 10.602f)
                lineTo(10.933f, 14.731f)
                cubicTo(11.5991f, 15.0898f, 12.4009f, 15.0898f, 13.067f, 14.731f)
                lineTo(20.735f, 10.601f)
                lineTo(22.105f, 11.34f)
                cubicTo(22.3476f, 11.4709f, 22.4988f, 11.7244f, 22.4988f, 12f)
                cubicTo(22.4988f, 12.2756f, 22.3476f, 12.5291f, 22.105f, 12.66f)
                lineTo(12.355f, 17.91f)
                cubicTo(12.1333f, 18.0291f, 11.8667f, 18.0291f, 11.645f, 17.91f)
                lineTo(1.895f, 12.66f)
                cubicTo(1.6524f, 12.5291f, 1.5012f, 12.2756f, 1.5012f, 12f)
                cubicTo(1.5012f, 11.7244f, 1.6524f, 11.4709f, 1.895f, 11.34f)
                lineTo(3.265f, 10.602f)
                close()
            }
            path {
                moveTo(10.933f, 19.231f)
                lineTo(3.265f, 15.101f)
                lineTo(1.895f, 15.84f)
                cubicTo(1.6524f, 15.9709f, 1.5012f, 16.2244f, 1.5012f, 16.5f)
                cubicTo(1.5012f, 16.7756f, 1.6524f, 17.0291f, 1.895f, 17.16f)
                lineTo(11.645f, 22.41f)
                cubicTo(11.866f, 22.53f, 12.134f, 22.53f, 12.355f, 22.41f)
                lineTo(22.105f, 17.16f)
                cubicTo(22.3476f, 17.0291f, 22.4988f, 16.7756f, 22.4988f, 16.5f)
                cubicTo(22.4988f, 16.2244f, 22.3476f, 15.9709f, 22.105f, 15.84f)
                lineTo(20.735f, 15.102f)
                lineTo(13.067f, 19.232f)
                cubicTo(12.4007f, 19.5905f, 11.5989f, 19.5901f, 10.933f, 19.231f)
                close()
            }
        }
    }

    /** Heroicons' `24/outline` tier -- stroke-only glyphs (`stroke-width="1.5"`,
     * `stroke-linecap="round"`, `stroke-linejoin="round"` on the `<svg>` root), converted to a
     * fillable outline at draw time by `icon()`. */
    object Outline24 {
        /** Heroicons `academic-cap` (24/outline), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val academicCap: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path(
                stroke = UiStroke(
                    width = 1.5f.dp,
                    cap = UiStrokeCap.Round,
                    join = UiStrokeJoin.Round,
                ),
            ) {
                moveTo(4.26f, 10.147f)
                cubicTo(3.9849f, 12.2526f, 3.8211f, 14.3712f, 3.769f, 16.494f)
                cubicTo(6.6478f, 17.6965f, 9.4042f, 19.1733f, 12f, 20.904f)
                cubicTo(14.5961f, 19.1733f, 17.3529f, 17.6965f, 20.232f, 16.494f)
                cubicTo(20.1799f, 14.3712f, 20.016f, 12.2526f, 19.741f, 10.147f)
                moveTo(4.259f, 10.147f)
                cubicTo(3.3806f, 9.8517f, 2.4943f, 9.5806f, 1.601f, 9.334f)
                cubicTo(4.8644f, 7.0459f, 8.348f, 5.0892f, 12f, 3.493f)
                cubicTo(15.652f, 5.0889f, 19.1356f, 7.0452f, 22.399f, 9.333f)
                cubicTo(21.503f, 9.581f, 20.616f, 9.853f, 19.741f, 10.147f)
                moveTo(4.259f, 10.147f)
                cubicTo(6.9276f, 11.0442f, 9.5169f, 12.1621f, 12f, 13.489f)
                cubicTo(14.4827f, 12.1621f, 17.0717f, 11.0442f, 19.74f, 10.147f)
                moveTo(6.75f, 15f)
                cubicTo(7.1642f, 15f, 7.5f, 14.6642f, 7.5f, 14.25f)
                cubicTo(7.5f, 13.8358f, 7.1642f, 13.5f, 6.75f, 13.5f)
                cubicTo(6.3358f, 13.5f, 6f, 13.8358f, 6f, 14.25f)
                cubicTo(6f, 14.6642f, 6.3358f, 15f, 6.75f, 15f)
                close()
                moveTo(6.75f, 15f)
                lineTo(6.75f, 11.325f)
                cubicTo(8.4467f, 10.2703f, 10.1993f, 9.3083f, 12f, 8.443f)
                moveTo(4.993f, 19.993f)
                cubicTo(6.12f, 18.8688f, 6.7523f, 17.3418f, 6.75f, 15.75f)
                lineTo(6.75f, 14.25f)
            }
        }

        /** Heroicons `clock` (24/outline), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val clock: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path(
                stroke = UiStroke(
                    width = 1.5f.dp,
                    cap = UiStrokeCap.Round,
                    join = UiStrokeJoin.Round,
                ),
            ) {
                moveTo(12f, 6f)
                lineTo(12f, 12f)
                lineTo(16.5f, 12f)
                moveTo(21f, 12f)
                cubicTo(21f, 16.9706f, 16.9706f, 21f, 12f, 21f)
                cubicTo(7.0294f, 21f, 3f, 16.9706f, 3f, 12f)
                cubicTo(3f, 7.0294f, 7.0294f, 3f, 12f, 3f)
                cubicTo(16.9706f, 3f, 21f, 7.0294f, 21f, 12f)
                close()
            }
        }

        /** Heroicons `camera` (24/outline), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val camera: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path(
                stroke = UiStroke(
                    width = 1.5f.dp,
                    cap = UiStrokeCap.Round,
                    join = UiStrokeJoin.Round,
                ),
            ) {
                moveTo(6.827f, 6.175f)
                cubicTo(6.4626f, 6.7517f, 5.8619f, 7.1379f, 5.186f, 7.23f)
                cubicTo(4.806f, 7.284f, 4.429f, 7.342f, 4.052f, 7.405f)
                cubicTo(2.999f, 7.58f, 2.25f, 8.507f, 2.25f, 9.574f)
                lineTo(2.25f, 18f)
                cubicTo(2.25f, 19.2426f, 3.2574f, 20.25f, 4.5f, 20.25f)
                lineTo(19.5f, 20.25f)
                cubicTo(20.7426f, 20.25f, 21.75f, 19.2426f, 21.75f, 18f)
                lineTo(21.75f, 9.574f)
                cubicTo(21.75f, 8.507f, 21f, 7.58f, 19.948f, 7.405f)
                cubicTo(19.5707f, 7.3421f, 19.1927f, 7.2838f, 18.814f, 7.23f)
                cubicTo(18.1384f, 7.1376f, 17.5382f, 6.7515f, 17.174f, 6.175f)
                lineTo(16.352f, 4.859f)
                cubicTo(15.9773f, 4.2504f, 15.3294f, 3.8626f, 14.616f, 3.82f)
                cubicTo(12.8733f, 3.7264f, 11.1267f, 3.7264f, 9.384f, 3.82f)
                cubicTo(8.6706f, 3.8626f, 8.0227f, 4.2504f, 7.648f, 4.859f)
                lineTo(6.827f, 6.175f)
                close()
            }
            path(
                stroke = UiStroke(
                    width = 1.5f.dp,
                    cap = UiStrokeCap.Round,
                    join = UiStrokeJoin.Round,
                ),
            ) {
                moveTo(16.5f, 12.75f)
                cubicTo(16.5f, 15.2353f, 14.4853f, 17.25f, 12f, 17.25f)
                cubicTo(9.5147f, 17.25f, 7.5f, 15.2353f, 7.5f, 12.75f)
                cubicTo(7.5f, 10.2647f, 9.5147f, 8.25f, 12f, 8.25f)
                cubicTo(14.4853f, 8.25f, 16.5f, 10.2647f, 16.5f, 12.75f)
                close()
                moveTo(18.75f, 10.5f)
                lineTo(18.758f, 10.5f)
                lineTo(18.758f, 10.508f)
                lineTo(18.75f, 10.508f)
                lineTo(18.75f, 10.5f)
                close()
            }
        }

        /** Heroicons `arrow-path` (24/outline), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val arrowPath: UiImageVector = uiImageVector(
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ) {
            path(
                stroke = UiStroke(
                    width = 1.5f.dp,
                    cap = UiStrokeCap.Round,
                    join = UiStrokeJoin.Round,
                ),
            ) {
                moveTo(16.023f, 9.348f)
                lineTo(21.015f, 9.348f)
                lineTo(21.015f, 9.347f)
                moveTo(2.985f, 19.644f)
                lineTo(2.985f, 14.652f)
                moveTo(2.985f, 14.652f)
                lineTo(7.977f, 14.652f)
                moveTo(2.984f, 14.652f)
                lineTo(6.165f, 17.835f)
                cubicTo(8.2494f, 19.9194f, 11.2875f, 20.7333f, 14.1347f, 19.9701f)
                cubicTo(16.982f, 19.2069f, 19.2057f, 16.9825f, 19.968f, 14.135f)
                moveTo(4.031f, 9.865f)
                cubicTo(4.7933f, 7.0175f, 7.017f, 4.7931f, 9.8643f, 4.0299f)
                cubicTo(12.7115f, 3.2667f, 15.7496f, 4.0806f, 17.834f, 6.165f)
                lineTo(21.015f, 9.347f)
                moveTo(21.015f, 4.356f)
                lineTo(21.015f, 9.346f)
            }
        }
    }
}
