/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package io.github.awakelab.awake.vulkan

import io.github.awakelab.awake.core.geometry.MeshGeometry
import io.github.awakelab.awake.core.geometry.VertexFormat
import io.github.awakelab.awake.core.host.readResourceBytes
import io.github.awakelab.awake.core.math.Lens
import io.github.awakelab.awake.core.math.Mat4
import io.github.awakelab.awake.core.math.Vec3f
import io.github.awakelab.awake.render.passes.OpaqueRenderFeature
import io.github.awakelab.awake.render.passes2d.UiRenderFeature
import io.github.awakelab.awake.render.renderer.DrawCall
import io.github.awakelab.awake.render.testing.comparePixels
import io.github.awakelab.awake.vulkan.commands.TransferContext
import io.github.awakelab.awake.vulkan.debug.LineRenderPipeline
import io.github.awakelab.awake.vulkan.device.GraphicsDevice
import io.github.awakelab.awake.vulkan.gen.VulkanDescriptors
import io.github.awakelab.awake.vulkan.material.Material
import io.github.awakelab.awake.vulkan.pipeline.PipelineTable
import io.github.awakelab.awake.vulkan.pipeline.RenderPipeline
import io.github.awakelab.awake.vulkan.pipeline.ShaderPair
import io.github.awakelab.awake.vulkan.pipeline.UiShaderPairs
import io.github.awakelab.awake.vulkan.pipeline.VulkanLinePass
import io.github.awakelab.awake.vulkan.pipeline.VulkanUiPass
import io.github.awakelab.awake.vulkan.pipeline.createSceneRenderPass
import io.github.awakelab.awake.vulkan.renderer.Renderer
import io.github.awakelab.awake.vulkan.swapchain.SwapchainManager
import kotlinx.coroutines.runBlocking
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlin.test.assertTrue
import io.github.awakelab.awake.render.material.Material as RenderMaterial
import io.github.awakelab.awake.render.mesh.Mesh as RenderMesh

/**
 * Proves the headless construction path ([GraphicsDevice.createHeadless]/
 * [SwapchainManager.createHeadless]) actually renders real geometry end to end, purely inside
 * a JVM test process -- no GLFW window, no `VkSurfaceKHR`, no swapchain, ever created. Renders
 * a cube from the same offscreen-verification camera angle
 * `DemoCatalog.verifyOffscreenReadback()` already uses on real hardware, then compares the
 * readback against a committed golden baseline via `awake:engine:testing`'s [comparePixels].
 *
 * Wired the same way [VulkanDesktopNativeSmokeTest] already is (this module's own `desktopTest`
 * task sets `-Djava.library.path`/`VK_ICD_FILENAMES`/`DYLD_FALLBACK_LIBRARY_PATH` -- see
 * build.gradle.kts) -- no new native-library wiring needed.
 *
 * The baseline (`src/desktopTest/resources/baselines/cube-headless.rgba`) was generated by a
 * one-time run of this exact test/render path on real hardware (Vulkan-over-MoltenVK, macOS)
 * and committed alongside it, per docs/archive/mvp-phase-log.md's Phase 2
 * pixel-baseline-testing entry.
 *
 * It was re-recorded once, when the committed `.spv` this test used to load were deleted. Those
 * had been compiled from a `triangle.wgsl` one revision old -- two vertex inputs, unlit -- and
 * they shadowed the canonical shader-pack copy, so the baseline captured a shader the engine
 * had stopped shipping. The cube is Lambertian-shaded now because the real shader always was.
 */

private fun writeRgbaPng(pixels: ByteArray, width: Int, height: Int, file: File) {
    val image = BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB)
    var offset = 0
    for (y in 0 until height) {
        for (x in 0 until width) {
            val r = pixels[offset].toInt() and 0xFF
            val g = pixels[offset + 1].toInt() and 0xFF
            val b = pixels[offset + 2].toInt() and 0xFF
            val a = pixels[offset + 3].toInt() and 0xFF
            image.setRGB(x, y, (a shl 24) or (r shl 16) or (g shl 8) or b)
            offset += 4
        }
    }
    ImageIO.write(image, "png", file)
}

class RendererHeadlessPixelBaselineTest {

    @Test
    fun headlessCubeRenderMatchesBaseline() {
        val graphicsDevice = GraphicsDevice()
        graphicsDevice.createHeadless()
        val swapchainManager = SwapchainManager(graphicsDevice, MAX_FRAMES_IN_FLIGHT)
        swapchainManager.createHeadless(TARGET_SIZE, TARGET_SIZE)
        val pipelineLayoutMaterial = Material(graphicsDevice)
        val sceneRenderPass = createSceneRenderPass(graphicsDevice, swapchainManager)
        val renderPipeline = RenderPipeline(
            graphicsDevice,
            swapchainManager,
            sceneRenderPass,
            pipelineLayoutMaterial.descriptorSetLayout,
            runBlocking {
                packShaderPair("triangle")
            },
            VertexFormat.PositionNormalColor,
            vertexEntryPoint = "vertexMain",
            fragmentEntryPoint = "fragmentMain",
        )
        val lineRenderPipeline = LineRenderPipeline(
            graphicsDevice,
            swapchainManager,
            sceneRenderPass,
            runBlocking {
                packShaderPair("debug_line")
            },
            MAX_FRAMES_IN_FLIGHT,
        )
        val transferContext = TransferContext(graphicsDevice)
        val renderer = Renderer(
            graphicsDevice = graphicsDevice,
            swapchainManager = swapchainManager,
            pipelines = PipelineTable(
                primary = renderPipeline,
                primaryFormat = renderPipeline.vertexFormat,
            ),
            renderFeatures = listOf(
                OpaqueRenderFeature(VulkanLinePass(lineRenderPipeline)),
                UiRenderFeature(VulkanUiPass()),
            ),
            transferContext = transferContext,
            uiShaderPairs = UiShaderPairs(
                quad = runBlocking {
                    packShaderPair("ui_quad")
                },
                glyph = runBlocking {
                    packShaderPair("ui_glyph")
                },
                texture = runBlocking {
                    packShaderPair("ui_texture")
                },
                roundedQuad = runBlocking {
                    packShaderPair("ui_rounded_quad")
                },
            ),
            maxFramesInFlight = MAX_FRAMES_IN_FLIGHT,
        )

        var mesh: RenderMesh? = null
        var material: RenderMaterial? = null
        try {
            val target = renderer.createRenderTarget(TARGET_SIZE, TARGET_SIZE)
            val camera = Lens(
                eye = Vec3f(2.5f, 2f, 4f),
                center = Vec3f(0f, 0f, 0f),
                fovYRadians = 1f,
                near = 0.1f,
                far = 10f,
            )
            val createdMesh =
                renderer.createMesh(
                    // Explicit: MeshGeometry still defaults to PositionColorUv, whose 8-float
                    // stride would read this 9-float data as garbage geometry rather than fail.
                    MeshGeometry(cubeVertices, cubeIndices, VertexFormat.PositionNormalColor),
                ).also { mesh = it }
            val createdMaterial = renderer.createMaterial().also { material = it }
            renderer.renderToTexture(target, camera, listOf(DrawCall(createdMesh, createdMaterial)))
            val pixels = runBlocking { renderer.readPixels(target) }

            if (System.getProperty("AWAKE_RECORD_SNAPSHOTS")?.toBoolean() == true) {
                File("src/desktopTest/resources/$BASELINE_RESOURCE_PATH").writeBytes(pixels.data)
            } else {
                val baseline = runBlocking { readResourceBytes(BASELINE_RESOURCE_PATH) }
                val result = comparePixels(pixels.data, baseline)
                if (!result.matches) {
                    // Dump both PNGs next to the test's own failure output so a developer can
                    // actually look at what rendered, instead of only reading a diff-pixel count --
                    // findable from the assertion message below without digging through Gradle's
                    // build directory structure.
                    val failureDir =
                        File("build/test-failures/RendererHeadlessPixelBaselineTest").apply { mkdirs() }
                    val actualPngFile = File(failureDir, "actual.png")
                    val baselinePngFile = File(failureDir, "baseline.png")
                    writeRgbaPng(pixels.data, TARGET_SIZE, TARGET_SIZE, actualPngFile)
                    writeRgbaPng(baseline, TARGET_SIZE, TARGET_SIZE, baselinePngFile)
                    assertTrue(
                        false,
                        "Headless cube render diverged from baseline: ${result.diffPixelCount} pixels differ " +
                            "(max channel diff ${result.maxChannelDiff}). Compare ${actualPngFile.absolutePath} " +
                            "against ${baselinePngFile.absolutePath}. Re-record $BASELINE_RESOURCE_PATH if this " +
                            "divergence is an intentional rendering change.",
                    )
                }
            }

            // Regression coverage for DrawCall's documented "mesh/material may be shared"
            // contract. Before materials had per-draw uniform slots, the second MVP rewrite
            // could overwrite the first draw before the GPU consumed it, collapsing both cubes
            // onto the last transform.
            renderer.renderToTexture(
                target,
                camera,
                listOf(
                    DrawCall(
                        createdMesh,
                        createdMaterial,
                        Mat4().translate(-SHARED_CUBE_OFFSET_X, 0f, 0f),
                    ),
                    DrawCall(
                        createdMesh,
                        createdMaterial,
                        Mat4().translate(SHARED_CUBE_OFFSET_X, 0f, 0f),
                    ),
                ),
            )
            val sharedMaterialPixels = runBlocking { renderer.readPixels(target) }
            val leftPainted = countPaintedPixels(
                sharedMaterialPixels.data,
                xRange = SHARED_MATERIAL_LEFT_X,
                yRange = SHARED_MATERIAL_Y,
            )
            val rightPainted = countPaintedPixels(
                sharedMaterialPixels.data,
                xRange = SHARED_MATERIAL_RIGHT_X,
                yRange = SHARED_MATERIAL_Y,
            )

            assertTrue(
                leftPainted > MIN_SHARED_MATERIAL_REGION_PIXELS,
                "left cube should render with the shared material's first transform, " +
                    "but only $leftPainted pixels were painted",
            )
            assertTrue(
                rightPainted > MIN_SHARED_MATERIAL_REGION_PIXELS,
                "right cube should render with the shared material's second transform, " +
                    "but only $rightPainted pixels were painted",
            )
        } finally {
            // Symmetric with VulkanEngine.destroyBackend()'s own teardown order: a
            // demo/game owns createMesh()/createMaterial()'s destroy() calls (Renderer doesn't
            // track them, see Renderer.createMaterial's doc comment), same here.
            mesh?.destroy()
            material?.destroy()
            renderer.destroy()
            renderPipeline.destroy()
            // pipelineLayoutMaterial never had createResources() called (only its
            // descriptorSetLayout was ever used, to build renderPipeline's pipeline layout) --
            // same reasoning as VulkanEngine.destroyBackend()'s own pipelineLayoutMaterial
            // teardown, so only the layout itself is destroyed here, not the full Material.
            VulkanDescriptors.vkDestroyDescriptorSetLayout(
                graphicsDevice.device,
                pipelineLayoutMaterial.descriptorSetLayout.handle,
            )
            transferContext.destroy()
            Vulkan.vkDestroyRenderPass(graphicsDevice.device, sceneRenderPass)
            graphicsDevice.destroy()
        }
    }

    private fun countPaintedPixels(pixels: ByteArray, xRange: IntRange, yRange: IntRange): Int {
        var count = 0
        for (y in yRange) {
            for (x in xRange) {
                val offset = (y * TARGET_SIZE + x) * 4
                val r = pixels[offset].toInt() and 0xFF
                val g = pixels[offset + 1].toInt() and 0xFF
                val b = pixels[offset + 2].toInt() and 0xFF
                if (r > PAINTED_CHANNEL_THRESHOLD || g > PAINTED_CHANNEL_THRESHOLD || b > PAINTED_CHANNEL_THRESHOLD) {
                    count += 1
                }
            }
        }
        return count
    }

    private companion object {
        const val TARGET_SIZE = 128
        const val MAX_FRAMES_IN_FLIGHT = 1
        const val BASELINE_RESOURCE_PATH = "baselines/cube-headless.rgba"
        const val MIN_SHARED_MATERIAL_REGION_PIXELS = 20
        const val PAINTED_CHANNEL_THRESHOLD = 8
        const val SHARED_CUBE_OFFSET_X = 0.9f
        const val SHARED_MATERIAL_LEFT_MIN_X = 18
        const val SHARED_MATERIAL_LEFT_MAX_X = 58
        const val SHARED_MATERIAL_RIGHT_MIN_X = 70
        const val SHARED_MATERIAL_RIGHT_MAX_X = 110
        const val SHARED_MATERIAL_MIN_Y = 32
        const val SHARED_MATERIAL_MAX_Y = 96
        val SHARED_MATERIAL_LEFT_X = SHARED_MATERIAL_LEFT_MIN_X until SHARED_MATERIAL_LEFT_MAX_X
        val SHARED_MATERIAL_RIGHT_X = SHARED_MATERIAL_RIGHT_MIN_X until SHARED_MATERIAL_RIGHT_MAX_X
        val SHARED_MATERIAL_Y = SHARED_MATERIAL_MIN_Y until SHARED_MATERIAL_MAX_Y

        /** 1/sqrt(3) -- a corner's outward direction, all three components equal. */
        const val CORNER_NORMAL = 0.57735026f

        /**
         * Position, normal, colour per vertex: the layout `triangle.wgsl` declares.
         *
         * Was position/colour/uv until the committed `.spv` this test loaded went away. Those
         * were a revision behind the canonical shader -- two vertex inputs where it now has
         * three -- so the test had been rendering a shader the engine no longer ships, and the
         * stale pair shadowed the real one. See this file's baseline note.
         *
         * Normals are the corner direction rather than a face normal, which keeps the cube at
         * eight vertices instead of twenty-four. Nothing here asserts lighting; the shading
         * only has to be deterministic.
         */
        val cubeVertices = floatArrayOf(
            -0.5f, -0.5f, -0.5f, -CORNER_NORMAL, -CORNER_NORMAL, -CORNER_NORMAL, 0f, 0f, 0f, // v0
            0.5f, -0.5f, -0.5f, CORNER_NORMAL, -CORNER_NORMAL, -CORNER_NORMAL, 1f, 0f, 0f, // v1
            0.5f, 0.5f, -0.5f, CORNER_NORMAL, CORNER_NORMAL, -CORNER_NORMAL, 1f, 1f, 0f, // v2
            -0.5f, 0.5f, -0.5f, -CORNER_NORMAL, CORNER_NORMAL, -CORNER_NORMAL, 0f, 1f, 0f, // v3
            -0.5f, -0.5f, 0.5f, -CORNER_NORMAL, -CORNER_NORMAL, CORNER_NORMAL, 0f, 0f, 1f, // v4
            0.5f, -0.5f, 0.5f, CORNER_NORMAL, -CORNER_NORMAL, CORNER_NORMAL, 1f, 0f, 1f, // v5
            0.5f, 0.5f, 0.5f, CORNER_NORMAL, CORNER_NORMAL, CORNER_NORMAL, 1f, 1f, 1f, // v6
            -0.5f, 0.5f, 0.5f, -CORNER_NORMAL, CORNER_NORMAL, CORNER_NORMAL, 0f, 1f, 1f, // v7
        )
        val cubeIndices = intArrayOf(
            0, 1, 2, 2, 3, 0, // back
            4, 5, 6, 6, 7, 4, // front
            0, 3, 7, 7, 4, 0, // left
            1, 5, 6, 6, 2, 1, // right
            0, 4, 5, 5, 1, 0, // bottom
            3, 2, 6, 6, 7, 3, // top
        )
    }
}
