// Copyright (c) Ron June Valdoz
// SPDX-License-Identifier: Apache-2.0
package io.github.ronjunevaldoz.awake.tailwindgenerator

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import java.io.File

private const val UI_PACKAGE = "io.github.ronjunevaldoz.awake.ui.api"
private const val TARGET_PACKAGE = "io.github.ronjunevaldoz.awake.ui.tailwind"

/** Manual/on-demand, matching `:awake:backend:vulkan:generator`'s own shape -- run this and
 * commit the regenerated `Tw.kt`, don't wire it into every build. */
fun main() {
    val dpClassName = ClassName(UI_PACKAGE, "Dp")
    val dpExtension = MemberName(UI_PACKAGE, "dp")

    val spacingObject = TypeSpec.objectBuilder("Spacing")
        .addKdoc(
            "Tailwind's default spacing scale (%L steps, %S through %S) -- see " +
                "`tailwindSpacingScalePx` in `:awake:ui:tailwind-generator` for the " +
                "vendored source and why radius isn't included here.",
            tailwindSpacingScalePx.size,
            tailwindSpacingScalePx.first().first,
            tailwindSpacingScalePx.last().first,
        )
        .apply {
            tailwindSpacingScalePx.forEach { (step, px) ->
                addProperty(
                    PropertySpec.builder(step.toPropertyName(), dpClassName)
                        .addKdoc("Tailwind scale step `%L` = %Lpx.", step, px)
                        .initializer("%L.%M", "${px}f", dpExtension)
                        .build(),
                )
            }
        }
        .build()

    val spClassName = ClassName(UI_PACKAGE, "Sp")
    val spExtension = MemberName(UI_PACKAGE, "sp")

    val radiusObject = TypeSpec.objectBuilder("Radius")
        .addKdoc("Tailwind border radius tokens.")
        .addProperty(PropertySpec.builder("none", dpClassName).initializer("0f.%M", dpExtension).build())
        .addProperty(PropertySpec.builder("sm", dpClassName).initializer("2f.%M", dpExtension).build())
        .addProperty(PropertySpec.builder("md", dpClassName).initializer("4f.%M", dpExtension).build())
        .addProperty(PropertySpec.builder("lg", dpClassName).initializer("6f.%M", dpExtension).build())
        .addProperty(PropertySpec.builder("xl", dpClassName).initializer("8f.%M", dpExtension).build())
        .addProperty(PropertySpec.builder("`2xl`", dpClassName).initializer("12f.%M", dpExtension).build())
        .addProperty(PropertySpec.builder("`3xl`", dpClassName).initializer("16f.%M", dpExtension).build())
        .addProperty(PropertySpec.builder("full", dpClassName).initializer("9999f.%M", dpExtension).build())
        .build()

    val textObject = TypeSpec.objectBuilder("Text")
        .addKdoc("Tailwind font size tokens.")
        .addProperty(PropertySpec.builder("xs", spClassName).initializer("12f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("sm", spClassName).initializer("14f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("base", spClassName).initializer("16f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("lg", spClassName).initializer("18f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("xl", spClassName).initializer("20f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("`2xl`", spClassName).initializer("24f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("`3xl`", spClassName).initializer("30f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("`4xl`", spClassName).initializer("36f.%M", spExtension).build())
        .addProperty(PropertySpec.builder("`5xl`", spClassName).initializer("48f.%M", spExtension).build())
        .build()

    val twObject = TypeSpec.objectBuilder("Tw")
        .addKdoc(
            "Generated by `:awake:ui:tailwind-generator` -- do not hand-edit. Re-run " +
                "that module's `main()` and commit the diff if the vendored scale changes.",
        )
        .addType(spacingObject)
        .addType(radiusObject)
        .addType(textObject)
        .build()

    val fileSpec = FileSpec.builder(TARGET_PACKAGE, "Tw")
        .addFileComment("Copyright (c) Ron June Valdoz\nSPDX-License-Identifier: Apache-2.0\n")
        .addFileComment("GENERATED FILE -- see :awake:ui:tailwind-generator, do not hand-edit.")
        .addType(twObject)
        .build()

    val outputDir = File("../tailwind/src/commonMain/kotlin")
    fileSpec.writeTo(outputDir)
    println("Wrote ${outputDir.resolve(TARGET_PACKAGE.replace('.', '/')).resolve("Tw.kt")}")
}

/** Tailwind step names aren't all valid Kotlin identifiers on their own (`"0.5"`, and a bare
 * digit can't lead a Kotlin property name) -- `"0.5"` -> `s0_5`, `"9"` -> `s9`, `"px"` stays
 * `px` (already a valid, distinct identifier). */
private fun String.toPropertyName(): String =
    if (this == "px") "px" else "s${replace('.', '_')}"
