// Serves a module's resource directories to test runtimes that get no resource processing
// from Kotlin itself:
//  - Kotlin/Native test binaries run from build/bin/<target>/debugTest and readResourceBytes'
//    iOS actual resolves paths against that directory -- nothing copies resources there.
//  - Karma runs wasm browser tests from build/wasm/packages/<module>-test at the ROOT build
//    directory and serves nothing else -- readResourceBytes' fetch() 404s.
// Apply the plugin and list the roots:
//     awakeTestResources { roots.from(layout.projectDirectory.dir("src/commonMain/resources")) }
// The karma snippet is generated (machine-local absolute paths) and gitignored.

interface AwakeTestResourcesExtension {
    val roots: ConfigurableFileCollection
}

val awakeTestResources = extensions.create<AwakeTestResourcesExtension>("awakeTestResources")

val copyIosSimulatorTestResources = tasks.register<Copy>("copyIosSimulatorTestResources") {
    from(awakeTestResources.roots)
    into(layout.buildDirectory.dir("bin/iosSimulatorArm64/debugTest"))
}

tasks.matching { it.name == "iosSimulatorArm64Test" }.configureEach {
    dependsOn(copyIosSimulatorTestResources)
}

val karmaSnippet = layout.projectDirectory.file("karma.config.d/awake-serve-test-resources.js")

val generateAwakeKarmaTestResources = tasks.register("generateAwakeKarmaTestResources") {
    inputs.files(awakeTestResources.roots)
    outputs.file(karmaSnippet)
    doLast {
        val roots = awakeTestResources.roots.files.filter { it.isDirectory }
        val lines = StringBuilder()
        lines.append("// Generated by awake.test-resources-convention -- do not edit, gitignored.\n")
        lines.append("config.proxies = config.proxies || {};\n")
        roots.forEach { root ->
            lines.append("config.files.push({ pattern: ${'"'}${root.absolutePath}/**/*${'"'}, included: false, served: true, watched: false });\n")
            // One proxy per top-level entry: fetch() paths are relative to karma's basePath,
            // which is nowhere near the module, so each entry maps back to its absolute source.
            root.listFiles()?.sortedBy { it.name }?.forEach { entry ->
                val suffix = if (entry.isDirectory) "/" else ""
                lines.append("config.proxies[\"/${entry.name}$suffix\"] = \"/absolute${entry.absolutePath}$suffix\";\n")
            }
        }
        karmaSnippet.asFile.parentFile.mkdirs()
        karmaSnippet.asFile.writeText(lines.toString())
    }
}

tasks.matching { it.name == "wasmJsBrowserTest" }.configureEach {
    dependsOn(generateAwakeKarmaTestResources)
}
