// Serves a module's resource directories to test runtimes that get no resource processing
// from Kotlin itself:
//  - Kotlin/Native test binaries run from build/bin/<target>/debugTest and readResourceBytes'
//    iOS actual resolves paths against that directory -- nothing copies resources there.
//  - Karma runs wasm browser tests from build/wasm/packages/<module>-test at the ROOT build
//    directory and serves nothing else -- readResourceBytes' fetch() 404s.
// Apply the plugin and list the roots:
//     awakeTestResources { roots.from(layout.projectDirectory.dir("src/commonMain/resources")) }
// The karma snippet is generated (machine-local absolute paths) and gitignored.

interface AwakeTestResourcesExtension {
    val roots: ConfigurableFileCollection
}

val awakeTestResources = extensions.create<AwakeTestResourcesExtension>("awakeTestResources")

val copyIosSimulatorTestResources = tasks.register<Copy>("copyIosSimulatorTestResources") {
    from(awakeTestResources.roots)
    into(layout.buildDirectory.dir("bin/iosSimulatorArm64/debugTest"))
}

tasks.matching { it.name == "iosSimulatorArm64Test" }.configureEach {
    dependsOn(copyIosSimulatorTestResources)
}

val karmaSnippet = layout.projectDirectory.file("karma.config.d/awake-serve-test-resources.js")

// Merge every root into one tree first, THEN generate proxies from the merge -- proxying each
// root's live source directly (one proxy entry per root, keyed by its top-level dir name) broke
// the moment two roots shared a top-level name (e.g. both commonMain/resources and appMain/
// resources have an assets/ dir): the second root's proxy silently overwrote the first's,
// stranding whatever the first root had that the second didn't (a model file with no matching
// scene document in the other root, or vice versa). A Sync merges same-named subtrees instead
// of one replacing the other.
val mergedTestResourcesDir = layout.buildDirectory.dir("awakeTestResources/wasmJs")

val syncAwakeTestResources = tasks.register<Sync>("syncAwakeTestResources") {
    from(awakeTestResources.roots)
    into(mergedTestResourcesDir)
}

val generateAwakeKarmaTestResources = tasks.register("generateAwakeKarmaTestResources") {
    dependsOn(syncAwakeTestResources)
    inputs.files(awakeTestResources.roots)
    outputs.file(karmaSnippet)
    doLast {
        val merged = mergedTestResourcesDir.get().asFile
        val lines = StringBuilder()
        lines.append("// Generated by awake.test-resources-convention -- do not edit, gitignored.\n")
        lines.append("config.proxies = config.proxies || {};\n")
        lines.append("config.files.push({ pattern: ${'"'}${merged.absolutePath}/**/*${'"'}, included: false, served: true, watched: false });\n")
        // One proxy per top-level entry in the MERGED tree: fetch() paths are relative to
        // karma's basePath, which is nowhere near the module, so each entry maps back to its
        // absolute merged location.
        merged.listFiles()?.sortedBy { it.name }?.forEach { entry ->
            val suffix = if (entry.isDirectory) "/" else ""
            lines.append("config.proxies[\"/${entry.name}$suffix\"] = \"/absolute${entry.absolutePath}$suffix\";\n")
        }
        karmaSnippet.asFile.parentFile.mkdirs()
        karmaSnippet.asFile.writeText(lines.toString())
    }
}

tasks.matching { it.name == "wasmJsBrowserTest" }.configureEach {
    dependsOn(generateAwakeKarmaTestResources)
}
