site_name: Awake Engine
site_url: https://ronjunevaldoz.github.io/awake/
repo_url: https://github.com/ronjunevaldoz/awake
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - content.code.copy
    - content.tabs.link
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides:
      - Theming: guides/theming.md
      - UI Components:
          - Buttons: guides/components/button.md
  - API Reference: api/index.html
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: [..] # Allow snippets from project root
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
