/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package io.github.awakelab.awake.vulkan.enums

enum class VkPipelineBindPoint(val value: Int) {
    VK_PIPELINE_BIND_POINT_GRAPHICS(0),
    VK_PIPELINE_BIND_POINT_COMPUTE(1),
    VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR(1000165000),
    VK_PIPELINE_BIND_POINT_SUBPASS_SHADING_HUAWEI(1000369003),
    VK_PIPELINE_BIND_POINT_RAY_TRACING_NV(VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR.value),
    VK_PIPELINE_BIND_POINT_MAX_ENUM(0x7FFFFFFF),
}
