// Copyright (c) Ron June Valdoz
// SPDX-License-Identifier: Apache-2.0
package io.github.ronjunevaldoz.awake.tailwindgenerator

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import java.io.File

private const val UI_PACKAGE = "io.github.ronjunevaldoz.awake.ui"
private const val TARGET_PACKAGE = "io.github.ronjunevaldoz.awake.ui.tailwind"

/** Manual/on-demand, matching `:awake:backend:vulkan:generator`'s own shape -- run this and
 * commit the regenerated `Tw.kt`, don't wire it into every build. */
fun main() {
    val dpClassName = ClassName(UI_PACKAGE, "Dp")
    val dpExtension = MemberName(UI_PACKAGE, "dp")

    val spacingObject = TypeSpec.objectBuilder("Spacing")
        .addKdoc(
            "Tailwind's default spacing scale (%L steps, %S through %S) -- see " +
                "`tailwindSpacingScalePx` in `:awake:engine:ui:tailwind-generator` for the " +
                "vendored source and why radius isn't included here.",
            tailwindSpacingScalePx.size,
            tailwindSpacingScalePx.first().first,
            tailwindSpacingScalePx.last().first,
        )
        .apply {
            tailwindSpacingScalePx.forEach { (step, px) ->
                addProperty(
                    PropertySpec.builder(step.toPropertyName(), dpClassName)
                        .addKdoc("Tailwind scale step `%L` = %Lpx.", step, px)
                        .initializer("%L.%M", "${px}f", dpExtension)
                        .build(),
                )
            }
        }
        .build()

    val twObject = TypeSpec.objectBuilder("Tw")
        .addKdoc(
            "Generated by `:awake:engine:ui:tailwind-generator` -- do not hand-edit. Re-run " +
                "that module's `main()` and commit the diff if the vendored scale changes.",
        )
        .addType(spacingObject)
        .build()

    val fileSpec = FileSpec.builder(TARGET_PACKAGE, "Tw")
        .addFileComment("Copyright (c) Ron June Valdoz\nSPDX-License-Identifier: Apache-2.0\n")
        .addFileComment("GENERATED FILE -- see :awake:engine:ui:tailwind-generator, do not hand-edit.")
        .addType(twObject)
        .build()

    val outputDir = File("../ui-core/src/commonMain/kotlin")
    fileSpec.writeTo(outputDir)
    println("Wrote ${outputDir.resolve(TARGET_PACKAGE.replace('.', '/')).resolve("Tw.kt")}")
}

/** Tailwind step names aren't all valid Kotlin identifiers on their own (`"0.5"`, and a bare
 * digit can't lead a Kotlin property name) -- `"0.5"` -> `s0_5`, `"9"` -> `s9`, `"px"` stays
 * `px` (already a valid, distinct identifier). */
private fun String.toPropertyName(): String =
    if (this == "px") "px" else "s${replace('.', '_')}"
