/*
 * SPDX-FileCopyrightText: 2023-2026 Ron June Valdoz
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.awakekt.awake.vulkan.enums.flags

import com.awakekt.awake.vulkan.VkFlags
import com.awakekt.awake.vulkan.enums.VkEnum

/**
 * The pipeline counters a pipeline-statistics query records (`VkQueryPipelineStatisticFlagBits`).
 *
 * @property value The raw integer value Vulkan uses for this constant.
 */
enum class VkQueryPipelineStatisticFlagBits(override val value: Int) : VkEnum {
    /** Vertices processed by input assembly. */
    VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT(0x00000001),

    /** Primitives processed by input assembly. */
    VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT(0x00000002),

    /** Vertex shader invocations. */
    VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT(0x00000004),

    /** Geometry shader invocations. */
    VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT(0x00000008),

    /** Primitives generated by the geometry shader. */
    VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT(0x00000010),

    /** Primitives that reached the clipping stage. */
    VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT(0x00000020),

    /** Primitives generated by the clipping stage. */
    VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT(0x00000040),

    /** Fragment shader invocations. */
    VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT(0x00000080),

    /** Patches processed by the tessellation control shader. */
    VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT(0x00000100),

    /** Tessellation evaluation shader invocations. */
    VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT(0x00000200),

    /** Compute shader invocations. */
    VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT(0x00000400),

    /** Sentinel that forces the C enum to 32 bits; it is never a valid value. */
    VK_QUERY_PIPELINE_STATISTIC_FLAG_BITS_MAX_ENUM(0x7FFFFFFF),
}

typealias VkQueryPipelineStatisticFlags = VkFlags
